### ISSUE TITLE
Error when running service_discovery.py

### ISSUE THREAD

**Issue by scorpi11** [hbldh/bleak#1069]
* bleak version: 0.18.1
* Python version: 3.10.6
* Operating System: Debian Sid
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.65

### Description

I run the supplied service_discovery.py to get information about a device.

I used in in the past with bleak 0.14 IIRC and it worked. Now it throws an error.
### What I Did

I started service-explorer.py.

```
$ python3 ./service_explorer.py 04:FE:A1:BA:C2:10
INFO:__main__:Connected: True
ERROR:root:A message handler raised an exception: 'Player'.
Traceback (most recent call last):
  File "/home/scorpion/.local/lib/python3.10/site-packages/dbus_fast/message_bus.py", line 737, in _process_message
    result = handler(msg)
  File "/usr/lib/python3/dist-packages/bleak/backends/bluezdbus/manager.py", line 790, in _parse_msg
    del self_interface[name]
KeyError: 'Player'
```

**Comment by dlech** [comment]
What is the output with `BLEAK_LOGGING=1`?
