### ISSUE TITLE
micro:bit disconnected after pairing (In JustWorks setting) and cannot connect to micro:bit again

### ISSUE THREAD

**Issue by BitaMatt** [hbldh/bleak#1076]
* bleak version: 0.18.1
* Python version: 3.10.7
* Operating System: Windows10

### Description

I want to connect to micro:bit using bleak's api in windows 10 OS. And use the

>  BleakClient.write_gatt_char 

to  send messge to the micro:bit Event Service (UUID: E95D93AF-251D-470A-A062-FA1922DFA9A8) (Which have Characteristic: 'E95D5404-251D-470A-A062-FA1922DFA9A8' to trigger the event I've been written and downloaded to micro:bit). Unfortunately I found out that I must paired with microbit in order to send message from my computer. So I used:

```
async with BleakClient(device,disconnected_callback=disconnected_callback,timeout=15.0) as client:
        print("Pairing Client")
        await client.pair()
        ....
        codes that use to send message
```

to pair with micro:bit.  I found out that micro:bit is successfully connect and pair with my computer. But after pairing finished, disconnected_callback called out (Though I saw it is still connected On Windows Bluetooth setting) 
![image](https://user-images.githubusercontent.com/52351304/195048749-0ba6ccdd-0d53-4e7d-8422-555037c3156c.png)
After that I add connect command after paired, and it always failed with **TimeoutError**:

```
 async with BleakClient(device,disconnected_callback=disconnected_callback,timeout=15.0) as client:
        print("Pairing Client")
        await pairClient(client)
        await asyncio.sleep(10)
        print("Reconnecting")
        print(f'is connect? {client.is_connected}')
        if not client.is_connected:
            await client.connect()
```
![image](https://user-images.githubusercontent.com/52351304/195059200-821b20c4-6422-417c-8c7a-102906fb557f.png)

### What I Did
This is an example code that micro:bit used
https://makecode.microbit.org/_1yFbXM6TyPxT

This is an brief python code (minimal code that can run) that I used to connect and pair with micro:bit :
```
import time
import asyncio
import logging
from bleak import BleakClient, BLEDevice, BleakGATTCharacteristic
from bleak import BleakScanner

#device pair tag
deviceChar = "zipeg"

disconnected_event = asyncio.Event()

def disconnected_callback(client):
    print("Disconnected callback called!")
    disconnected_event.set()

async def scanWithNamePart(wanted_name_part):
    '''
    Find device by specific string
    :param wanted_name_part:
    :return:
    '''
    device = await BleakScanner.find_device_by_filter(
        lambda d,ad: (wanted_name_part.lower() in d.name or wanted_name_part.lower() in d.name.lower()) if d.name is not None else False
    )
    print(device)
    device_data = device
    return device_data

async def mainCheck():
    #main function
    print("Discover device by name:")
    device: BLEDevice = await scanWithNamePart(deviceChar)
    if device is not None:
        print("Device Found!")
    else:
        print(f"Failed to discover device with string: {deviceChar}")
        return 0

    async with BleakClient(device,disconnected_callback=disconnected_callback,timeout=15.0) as client:
        print("Pairing Client")
        await client.pair()
        await asyncio.sleep(10)
        
        print(f'is connect? {client.is_connected}')
        if not client.is_connected:
            print("Reconnecting")
            await client.connect()
```

And the running result from Terminal:
'''
Discover device by name:
D1:09:0B:5C:D7:FC: BBC micro:bit [zipeg]
Device Found!
Pairing Client
INFO:bleak.backends.winrt.client:Services resolved for BleakClientWinRT (D1:09:0B:5C:D7:FC)
INFO:bleak.backends.winrt.client:Paired to device with protection level 1.
Disconnected callback called!
Reconnecting
is connect? False
Disconnected callback called!
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 331, in connect
    await event.wait()
  File "C:\Python310\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\microbit_control.py", line 271, in <module>
    asyncio.run(mainCheck())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\...\microbit_control.py", line 221, in mainCheck
    await client.connect()
  File "C:\Python310\lib\site-packages\bleak\__init__.py", line 392, in connect
    return await self._backend.connect(**kwargs)
  File "C:\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 330, in connect
    async with async_timeout.timeout(timeout):
  File "C:\Python310\lib\site-packages\async_timeout\__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "C:\Python310\lib\site-packages\async_timeout\__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

'''

### Logs
I opened Bleak_Logging andd this is the result:

```
Discover device by name:
2022-10-11 17:43:29,454 bleak.backends.winrt.scanner DEBUG: Received 7F:BA:14:5F:F8:35: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 7F:BA:14:5F:F8:35: Unknown.
2022-10-11 17:43:29,456 bleak.backends.winrt.scanner DEBUG: Received 7F:BA:14:5F:F8:35: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 7F:BA:14:5F:F8:35: Unknown.
2022-10-11 17:43:29,458 bleak.backends.winrt.scanner DEBUG: Received 4E:FB:74:B8:29:3C: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 4E:FB:74:B8:29:3C: Unknown.
2022-10-11 17:43:29,459 bleak.backends.winrt.scanner DEBUG: Received 4A:1E:A1:26:F4:50: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 4A:1E:A1:26:F4:50: Unknown.
2022-10-11 17:43:29,460 bleak.backends.winrt.scanner DEBUG: Received 4A:1E:A1:26:F4:50: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 4A:1E:A1:26:F4:50: Unknown.
2022-10-11 17:43:29,461 bleak.backends.winrt.scanner DEBUG: Received C0:00:00:11:40:7E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received C0:00:00:11:40:7E: Unknown.
2022-10-11 17:43:29,464 bleak.backends.winrt.scanner DEBUG: Received 5C:A7:C9:C4:04:3A: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 5C:A7:C9:C4:04:3A: Unknown.
2022-10-11 17:43:29,465 bleak.backends.winrt.scanner DEBUG: Received 5C:A7:C9:C4:04:3A: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 5C:A7:C9:C4:04:3A: Unknown.
2022-10-11 17:43:29,467 bleak.backends.winrt.scanner DEBUG: Received 46:4F:18:B2:E4:CF: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 46:4F:18:B2:E4:CF: Unknown.
2022-10-11 17:43:29,469 bleak.backends.winrt.scanner DEBUG: Received 46:4F:18:B2:E4:CF: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 46:4F:18:B2:E4:CF: Unknown.
2022-10-11 17:43:29,470 bleak.backends.winrt.scanner DEBUG: Received 09:99:4B:01:CD:3C: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 09:99:4B:01:CD:3C: Unknown.
2022-10-11 17:43:29,472 bleak.backends.winrt.scanner DEBUG: Received 29:18:E2:EB:C9:7D: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 29:18:E2:EB:C9:7D: Unknown.
2022-10-11 17:43:29,473 bleak.backends.winrt.scanner DEBUG: Received 0F:E9:A6:AE:17:19: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 0F:E9:A6:AE:17:19: Unknown.
2022-10-11 17:43:29,475 bleak.backends.winrt.scanner DEBUG: Received 0B:16:3D:50:42:BD: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 0B:16:3D:50:42:BD: Unknown.
2022-10-11 17:43:29,476 bleak.backends.winrt.scanner DEBUG: Received 06:0B:51:37:3C:77: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 06:0B:51:37:3C:77: Unknown.
2022-10-11 17:43:29,481 bleak.backends.winrt.scanner DEBUG: Received C0:00:00:11:40:7E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received C0:00:00:11:40:7E: Unknown.
2022-10-11 17:43:29,573 bleak.backends.winrt.scanner DEBUG: Received 61:FD:DA:F3:5B:5B: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 61:FD:DA:F3:5B:5B: Unknown.
2022-10-11 17:43:29,575 bleak.backends.winrt.scanner DEBUG: Received 61:FD:DA:F3:5B:5B: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 61:FD:DA:F3:5B:5B: Unknown.
2022-10-11 17:43:29,577 bleak.backends.winrt.scanner DEBUG: Received 0F:E9:A6:AE:17:19: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 0F:E9:A6:AE:17:19: Unknown.
2022-10-11 17:43:29,578 bleak.backends.winrt.scanner DEBUG: Received 29:18:E2:EB:C9:7D: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 29:18:E2:EB:C9:7D: Unknown.
2022-10-11 17:43:29,581 bleak.backends.winrt.scanner DEBUG: Received 75:A3:C8:DD:0B:24: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 75:A3:C8:DD:0B:24: Unknown.
2022-10-11 17:43:29,583 bleak.backends.winrt.scanner DEBUG: Received 06:0B:51:37:3C:77: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 06:0B:51:37:3C:77: Unknown.
2022-10-11 17:43:29,588 bleak.backends.winrt.scanner DEBUG: Received 6D:B2:A0:39:C6:93: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 6D:B2:A0:39:C6:93: Unknown.
2022-10-11 17:43:29,589 bleak.backends.winrt.scanner DEBUG: Received 6D:B2:A0:39:C6:93: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 6D:B2:A0:39:C6:93: Unknown.
2022-10-11 17:43:29,594 bleak.backends.winrt.scanner DEBUG: Received 4A:1E:A1:26:F4:50: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 4A:1E:A1:26:F4:50: Unknown.
2022-10-11 17:43:29,595 bleak.backends.winrt.scanner DEBUG: Received 4A:1E:A1:26:F4:50: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 4A:1E:A1:26:F4:50: Unknown.
2022-10-11 17:43:29,714 bleak.backends.winrt.scanner DEBUG: Received C0:00:00:11:40:7E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received C0:00:00:11:40:7E: Unknown.
2022-10-11 17:43:29,716 bleak.backends.winrt.scanner DEBUG: Received 76:FD:EF:61:02:C4: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 76:FD:EF:61:02:C4: Unknown.
2022-10-11 17:43:29,718 bleak.backends.winrt.scanner DEBUG: Received E9:49:CE:EC:44:B3: mobike.
DEBUG:bleak.backends.winrt.scanner:Received E9:49:CE:EC:44:B3: mobike.
2022-10-11 17:43:29,719 bleak.backends.winrt.scanner DEBUG: Received 69:D2:4E:A9:07:BA: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 69:D2:4E:A9:07:BA: Unknown.
2022-10-11 17:43:29,720 bleak.backends.winrt.scanner DEBUG: Received 69:D2:4E:A9:07:BA: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 69:D2:4E:A9:07:BA: Unknown.
2022-10-11 17:43:29,753 bleak.backends.winrt.scanner DEBUG: Received 25:F3:1E:DF:34:0D: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 25:F3:1E:DF:34:0D: Unknown.
2022-10-11 17:43:29,757 bleak.backends.winrt.scanner DEBUG: Received 6F:CA:44:42:9A:FB: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 6F:CA:44:42:9A:FB: Unknown.
2022-10-11 17:43:29,759 bleak.backends.winrt.scanner DEBUG: Received CA:1D:25:29:E2:C7: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received CA:1D:25:29:E2:C7: Unknown.
2022-10-11 17:43:29,760 bleak.backends.winrt.scanner DEBUG: Received C0:00:00:11:40:7E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received C0:00:00:11:40:7E: Unknown.
2022-10-11 17:43:29,803 bleak.backends.winrt.scanner DEBUG: Received 79:13:B2:67:E8:9E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 79:13:B2:67:E8:9E: Unknown.
2022-10-11 17:43:29,810 bleak.backends.winrt.scanner DEBUG: Received C0:00:00:11:40:7E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received C0:00:00:11:40:7E: Unknown.
2022-10-11 17:43:29,813 bleak.backends.winrt.scanner DEBUG: Received 46:4F:18:B2:E4:CF: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 46:4F:18:B2:E4:CF: Unknown.
2022-10-11 17:43:29,815 bleak.backends.winrt.scanner DEBUG: Received 46:4F:18:B2:E4:CF: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 46:4F:18:B2:E4:CF: Unknown.
2022-10-11 17:43:29,816 bleak.backends.winrt.scanner DEBUG: Received 69:90:EA:55:4C:CB: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 69:90:EA:55:4C:CB: Unknown.
2022-10-11 17:43:29,822 bleak.backends.winrt.scanner DEBUG: Received 12:76:BC:82:9C:33: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 12:76:BC:82:9C:33: Unknown.
2022-10-11 17:43:29,825 bleak.backends.winrt.scanner DEBUG: Received 7D:07:F2:06:19:E9: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 7D:07:F2:06:19:E9: Unknown.
2022-10-11 17:43:29,826 bleak.backends.winrt.scanner DEBUG: Received 7D:07:F2:06:19:E9: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 7D:07:F2:06:19:E9: Unknown.
2022-10-11 17:43:29,831 bleak.backends.winrt.scanner DEBUG: Received 7B:9D:B8:3D:F3:E4: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 7B:9D:B8:3D:F3:E4: Unknown.
2022-10-11 17:43:29,832 bleak.backends.winrt.scanner DEBUG: Received 22:F0:52:59:39:80: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 22:F0:52:59:39:80: Unknown.
2022-10-11 17:43:29,835 bleak.backends.winrt.scanner DEBUG: Received 10:6D:61:74:6F:3E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 10:6D:61:74:6F:3E: Unknown.
2022-10-11 17:43:29,931 bleak.backends.winrt.scanner DEBUG: Received 76:FD:EF:61:02:C4: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 76:FD:EF:61:02:C4: Unknown.
2022-10-11 17:43:29,933 bleak.backends.winrt.scanner DEBUG: Received 52:11:FA:6D:49:99: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 52:11:FA:6D:49:99: Unknown.
2022-10-11 17:43:29,934 bleak.backends.winrt.scanner DEBUG: Received 52:11:FA:6D:49:99: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 52:11:FA:6D:49:99: Unknown.
2022-10-11 17:43:29,935 bleak.backends.winrt.scanner DEBUG: Received 7B:9D:B8:3D:F3:E4: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 7B:9D:B8:3D:F3:E4: Unknown.
2022-10-11 17:43:29,938 bleak.backends.winrt.scanner DEBUG: Received 2F:F3:72:2E:1D:B1: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 2F:F3:72:2E:1D:B1: Unknown.
2022-10-11 17:43:29,940 bleak.backends.winrt.scanner DEBUG: Received C0:00:00:11:40:7E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received C0:00:00:11:40:7E: Unknown.
2022-10-11 17:43:29,941 bleak.backends.winrt.scanner DEBUG: Received 35:E5:49:CD:8F:64: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 35:E5:49:CD:8F:64: Unknown.
2022-10-11 17:43:29,944 bleak.backends.winrt.scanner DEBUG: Received 78:98:EA:20:D7:12: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 78:98:EA:20:D7:12: Unknown.
2022-10-11 17:43:30,038 bleak.backends.winrt.scanner DEBUG: Received 47:A7:E2:AB:31:15: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 47:A7:E2:AB:31:15: Unknown.
2022-10-11 17:43:30,039 bleak.backends.winrt.scanner DEBUG: Received 4F:23:8F:30:EA:37: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 4F:23:8F:30:EA:37: Unknown.
2022-10-11 17:43:30,042 bleak.backends.winrt.scanner DEBUG: Received 22:F0:52:59:39:80: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 22:F0:52:59:39:80: Unknown.
2022-10-11 17:43:30,045 bleak.backends.winrt.scanner DEBUG: Received 2D:85:E7:1C:7C:B1: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 2D:85:E7:1C:7C:B1: Unknown.
2022-10-11 17:43:30,048 bleak.backends.winrt.scanner DEBUG: Received 04:AA:82:2C:12:3A: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 04:AA:82:2C:12:3A: Unknown.
2022-10-11 17:43:30,050 bleak.backends.winrt.scanner DEBUG: Received 10:6D:61:74:6F:3E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 10:6D:61:74:6F:3E: Unknown.
2022-10-11 17:43:30,059 bleak.backends.winrt.scanner DEBUG: Received 46:4F:18:B2:E4:CF: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 46:4F:18:B2:E4:CF: Unknown.
2022-10-11 17:43:30,063 bleak.backends.winrt.scanner DEBUG: Received 46:4F:18:B2:E4:CF: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 46:4F:18:B2:E4:CF: Unknown.
2022-10-11 17:43:30,064 bleak.backends.winrt.scanner DEBUG: Received C0:00:00:11:40:7E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received C0:00:00:11:40:7E: Unknown.
2022-10-11 17:43:30,065 bleak.backends.winrt.scanner DEBUG: Received 25:F3:1E:DF:34:0D: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 25:F3:1E:DF:34:0D: Unknown.
2022-10-11 17:43:30,066 bleak.backends.winrt.scanner DEBUG: Received 0E:1D:AA:88:79:2E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 0E:1D:AA:88:79:2E: Unknown.
2022-10-11 17:43:30,159 bleak.backends.winrt.scanner DEBUG: Received 47:2E:86:D2:79:57: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 47:2E:86:D2:79:57: Unknown.
2022-10-11 17:43:30,161 bleak.backends.winrt.scanner DEBUG: Received 47:2E:86:D2:79:57: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 47:2E:86:D2:79:57: Unknown.
2022-10-11 17:43:30,164 bleak.backends.winrt.scanner DEBUG: Received C0:00:00:11:40:7E: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received C0:00:00:11:40:7E: Unknown.
2022-10-11 17:43:30,165 bleak.backends.winrt.scanner DEBUG: Received D1:09:0B:5C:D7:FC: BBC micro:bit [zipeg].
DEBUG:bleak.backends.winrt.scanner:Received D1:09:0B:5C:D7:FC: BBC micro:bit [zipeg].
2022-10-11 17:43:30,166 bleak.backends.winrt.scanner DEBUG: Received D1:09:0B:5C:D7:FC: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received D1:09:0B:5C:D7:FC: Unknown.
2022-10-11 17:43:30,167 bleak.backends.winrt.scanner DEBUG: Received 25:F3:1E:DF:34:0D: Unknown.
DEBUG:bleak.backends.winrt.scanner:Received 25:F3:1E:DF:34:0D: Unknown.
2022-10-11 17:43:30,168 bleak.backends.winrt.scanner DEBUG: 38 devices found. Watcher status: 3.
DEBUG:bleak.backends.winrt.scanner:38 devices found. Watcher status: 3.
D1:09:0B:5C:D7:FC: BBC micro:bit [zipeg]
Device Found!
2022-10-11 17:43:30,172 bleak.backends.winrt.client DEBUG: Connecting to BLE device @ D1:09:0B:5C:D7:FC
DEBUG:bleak.backends.winrt.client:Connecting to BLE device @ D1:09:0B:5C:D7:FC
2022-10-11 17:43:31,187 bleak.backends.winrt.client DEBUG: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x000001F0226453F0>, error: BluetoothError.SUCCESS, status: GattSessionStatus.ACTIVE
DEBUG:bleak.backends.winrt.client:session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x000001F0226453F0>, error: BluetoothError.SUCCESS, status: GattSessionStatus.ACTIVE
2022-10-11 17:43:31,190 bleak.backends.winrt.client DEBUG: Get Services...
DEBUG:bleak.backends.winrt.client:Get Services...
2022-10-11 17:43:34,525 bleak.backends.winrt.client INFO: Services resolved for BleakClientWinRT (D1:09:0B:5C:D7:FC)
INFO:bleak.backends.winrt.client:Services resolved for BleakClientWinRT (D1:09:0B:5C:D7:FC)
Pairing Client
2022-10-11 17:43:34,902 bleak.backends.winrt.client INFO: Paired to device with protection level 1.
INFO:bleak.backends.winrt.client:Paired to device with protection level 1.
2022-10-11 17:43:35,441 bleak.backends.winrt.client DEBUG: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x000001F022645430>, error: BluetoothError.SUCCESS, status: GattSessionStatus.CLOSED
DEBUG:bleak.backends.winrt.client:session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x000001F022645430>, error: BluetoothError.SUCCESS, status: GattSessionStatus.CLOSED
Disconnected callback called!
Reconnecting
is connect? False
2022-10-11 17:43:44,908 bleak.backends.winrt.client DEBUG: Connecting to BLE device @ D1:09:0B:5C:D7:FC
DEBUG:bleak.backends.winrt.client:Connecting to BLE device @ D1:09:0B:5C:D7:FC
2022-10-11 17:44:00,038 bleak.backends.winrt.client DEBUG: Disconnecting from BLE device...
DEBUG:bleak.backends.winrt.client:Disconnecting from BLE device...
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 331, in connect
    await event.wait()
  File "C:\Python310\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\microbit_control.py", line 271, in <module>
    asyncio.run(mainCheck())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\...\microbit_control.py", line 221, in mainCheck
    await client.connect()
  File "C:\Python310\lib\site-packages\bleak\__init__.py", line 392, in connect
    return await self._backend.connect(**kwargs)
  File "C:\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 330, in connect
    async with async_timeout.timeout(timeout):
  File "C:\Python310\lib\site-packages\async_timeout\__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "C:\Python310\lib\site-packages\async_timeout\__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

I almost done with using computer to control micro:bit with BluetoothLE! I would be very happy if this problem is solved!

**Comment by dlech** [comment]
Can you share logs of the Bluetooth packets captured with Wireshark as described in the troubleshooting page of the Bleak docs?

**Comment by BitaMatt** [comment]
> 

OK I will try it

**Comment by BitaMatt** [comment]
> Can you share logs of the Bluetooth packets captured with Wireshark as described in the troubleshooting page of the Bleak docs?

I followed the instruction of troubleshooting page and get this log file. 
[wireshark_log.zip](https://github.com/hbldh/bleak/files/9761203/wireshark_log.zip)

**Comment by dlech** [comment]
It looks like the MicroBit keeps sending the "Service Changed" indication, so Windows keeps re-enumerating the services. So I suspect a bug in the MicroBit firmware.

**Comment by BitaMatt** [comment]
> 

roger that , I will try to use another micro:bit for code testing

**Comment by BitaMatt** [comment]
> It looks like the MicroBit keeps sending the "Service Changed" indication, so Windows keeps re-enumerating the services. So I suspect a bug in the MicroBit firmware.

I finally find out the solution, just cancel the JustWork pairing mode and than I can control micro:bit without pairing with it! Thank you for your help!
