### ISSUE TITLE
python 3.11.0 - Module use of python39.dll conflicts with this version of Python

### ISSUE THREAD

**Issue by QuadCorei8085** [hbldh/bleak#1125]
* bleak version: (0.19.0)
* Python version: 3.11
* Operating System: Win10
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description, What I Did
Installed python 3.11.0 over python 3.9x and now I'm getting this error. I have zero clue how to fix this (google, stackoverflow got nothing too).

### Logs
Traceback (most recent call last):
  File "D:\projects\nucleo_ble\test\ble_dt.py", line 48, in <module>
    asyncio.run(main(address))
  File "C:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\projects\nucleo_ble\test\ble_dt.py", line 13, in main
    await discover();
    ^^^^^^^^^^^^^^^^
  File "D:\projects\nucleo_ble\test\ble_dt.py", line 8, in discover
    discover = await BleakScanner.discover();
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\bleak\__init__.py", line 216, in discover
    async with cls(**kwargs) as scanner:
               ^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\bleak\__init__.py", line 118, in __init__
    get_platform_scanner_backend_type() if backend is None else backend
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\bleak\backends\scanner.py", line 255, in get_platform_scanner_backend_type
    from bleak.backends.winrt.scanner import BleakScannerWinRT
  File "C:\Python\Lib\site-packages\bleak\backends\winrt\scanner.py", line 7, in <module>
    from bleak_winrt.windows.devices.bluetooth.advertisement import (
  File "C:\Python\Lib\site-packages\bleak_winrt\__init__.py", line 7, in <module>
    from . import _winrt
ImportError: Module use of python39.dll conflicts with this version of Python.

**Comment by QuadCorei8085** [comment]
pip install --ignore-installed bleak-winrt
