### ISSUE TITLE
'async with BleakClient() as client:' raises asyncio.TimeoutError on Raspberry Pi 3b+

### ISSUE THREAD

**Issue by ALindhardtJ** [hbldh/bleak#1139]
* bleak version: 0.19.5
* Python version: 3.9.2
* Operating System: Raspbian GNU/Linux 11 (bullseye)
* BlueZ version: 5.55

### Description

'async with bleak.BleakClient(address) as client:' raises asyncio.TimeoutError

### What I Did

I'm trying to connect to a GATT-server hosted on a ESP32-device, to receive some data. The following code works perfectly fine on my windows machine, however crashes on line 'async with bleak.BleakClient(address) as client:' when running it on my Raspberry Pi 3b+.

```python
import asyncio, bleak

msg = b'1'

async def main():
    devices = await bleak.BleakScanner.discover()
    for device in devices:
        if 'Foo' in device.name:
            myDevice = device
    address = myDevice.address
    
    async with bleak.BleakClient(address) as client:
        services = await client.get_services()
        for service in services:
            if str(service.description) == "Nordic UART Service":
                list_uuid = list(service.uuid)
                list_write_uuid = list_uuid
                list_read_uuid = list_uuid
                list_write_uuid[7] = "2"
                write_uuid = "".join(list_write_uuid)
                list_read_uuid[7] = "3"
                read_uuid = "".join(list_read_uuid)
        await client.start_notify(read_uuid, callback)
        await client.write_gatt_char(write_uuid, msg, True)
asyncio.run(main())
```
```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 172, in connect
    reply = await self._bus.call(
  File "/home/pi/.local/lib/python3.9/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/bleak_test.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/Desktop/bleak_test.py", line 10, in main
    async with bleak.BleakClient(address) as client:
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/__init__.py", line 433, in __aenter__
    await self.connect()
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/__init__.py", line 471, in connect
    return await self._backend.connect(**kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 172, in connect
    reply = await self._bus.call(
  File "/home/pi/.local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/home/pi/.local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError```

**Comment by dlech** [comment]
Have you tried anything from the troubleshooting page in the docs? (manually clearing BlueZ cache, debug logs, wireshark packet capture, etc.).

**Comment by ALindhardtJ** [comment]
So far i've only enabled logging, since i have not yet managed to establish connection between the two devices so clearing cache does not make much sense, and i'm afraid i'm not quite sure of how to capture the packets with Wireshark. However it does raise the error before connection is ever established. I'll look into it though.
I did not learn much from enabling logging, as it did not clarify for me why the TimeoutError occurs.
Any suggestions on how this function could be written without it crashing, is highly appreciated. Thank you.

**Comment by dlech** [comment]
We can't offer any insight if we can't see the logs. You could also try making the timeout longer.

**Comment by ALindhardtJ** [comment]
I decided to run the GATT server on the Raspberry Pi instead, so i won't be needing a solution to this problem of mine. I'm sorry for the inconvenience. Thank you for your time!
