### ISSUE TITLE
[WinError -2140864509] The attribute cannot be written, when trying to establish notifications.

### ISSUE THREAD

**Issue by olt96** [hbldh/bleak#1172]
* bleak version: 0.19.5
* Python version: 3.9.5, project interpreter 3.7.0
* Operating System:  
Edition	Windows 10 Pro
Version	20H2
Installed on	‎27-‎Dec-‎20
OS build	19042.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

### Description
 
Trying to get notifications to work for a custom BLE device (esp32).
Notifications work when testing from my phone, and the 2902 descriptor can be written to
However when trying to do the same with bleak, I get the following error
proof of notifications working on phone 
![image](https://user-images.githubusercontent.com/40365594/206972319-e311f4f5-016b-4f16-a3ef-0ee9a49bea82.png)

### What I Did
This is the testing BLE code that I have 
```
import asyncio
import bleak
#
BOARD_NAME = 'table_ble'
BOARD_STATE_CHARACTERISTIC_UUID = 'beb5483e-36e1-4688-b7f5-ea07361b26a8'

async def findTable():
    global TableDevice
    TableDevice = None
    print ("Searching for table...")
    while TableDevice == None:
        devices = await bleak.BleakScanner.discover()
        TableDevice = next((ble_device for ble_device in devices if ble_device.name == BOARD_NAME), None)
    print("table found!", TableDevice)

async def connectAndReceiveData():
    async with bleak.BleakClient(TableDevice) as client:
        print("Connected: {0}".format(client.is_connected))
        await client.start_notify(BOARD_STATE_CHARACTERISTIC_UUID, callback=newBoardStateReceived)
        await asyncio.sleep(10000000)

def newBoardStateReceived(sender: int, data: bytearray):
    print(f"{sender}: {data}")
    # Device will disconnect when block exits.
asyncio.run(findTable())
asyncio.run(connectAndReceiveData())

```

### Logs
```

Searching for table...
2022-12-12 07:04:01,708 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:01,708 bleak.backends.winrt.scanner DEBUG: skipping callback, waiting for scan response
2022-12-12 07:04:01,708 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:01,770 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:01,770 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:02,145 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:02,161 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:02,395 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:02,395 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:02,598 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:02,614 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:02,962 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:02,978 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,087 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,103 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,196 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,212 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,446 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,446 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,551 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,567 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,785 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:03,801 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:04,035 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:04,035 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:04,379 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:04,379 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:04,613 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:04,613 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:04,879 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:04,879 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,082 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,098 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,316 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,332 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,551 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,566 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,660 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,676 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,910 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:05,910 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:06,254 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:06,270 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:06,379 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:06,379 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:06,676 bleak.backends.winrt.scanner DEBUG: 1 devices found. Watcher status: 3.
2022-12-12 07:04:06,723 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:06,723 bleak.backends.winrt.scanner DEBUG: skipping callback, waiting for scan response
2022-12-12 07:04:06,738 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:06,973 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:06,973 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:07,316 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:07,332 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:07,426 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:07,441 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:07,899 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:07,915 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:08,133 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:08,133 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:08,383 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:08,383 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:08,727 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:08,743 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:08,961 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:08,961 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:09,305 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:09,321 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:09,555 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:09,555 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:09,665 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:09,665 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,133 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,133 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,368 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,368 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,493 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,508 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,633 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,649 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,836 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:10,852 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,180 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,196 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,305 bleak.backends.winrt.scanner DEBUG: Received 78:E3:6D:0B:30:AA: .
2022-12-12 07:04:11,305 bleak.backends.winrt.scanner DEBUG: skipping callback, waiting for scan response
2022-12-12 07:04:11,321 bleak.backends.winrt.scanner DEBUG: Received 78:E3:6D:0B:30:AA: table_ble.
2022-12-12 07:04:11,321 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,336 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,430 bleak.backends.winrt.scanner DEBUG: Received 78:E3:6D:0B:30:AA: .
2022-12-12 07:04:11,446 bleak.backends.winrt.scanner DEBUG: Received 78:E3:6D:0B:30:AA: table_ble.
2022-12-12 07:04:11,446 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,461 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,664 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,664 bleak.backends.winrt.scanner DEBUG: Received 38:18:4C:3D:18:A3: LE_WH-CH700N.
2022-12-12 07:04:11,696 bleak.backends.winrt.scanner DEBUG: 2 devices found. Watcher status: 3.
table found! 78:E3:6D:0B:30:AA: table_ble
2022-12-12 07:04:11,727 bleak.backends.winrt.client DEBUG: Connecting to BLE device @ 78:E3:6D:0B:30:AA
2022-12-12 07:04:11,836 bleak.backends.winrt.client DEBUG: getting services (service_cache_mode=None, cache_mode=None)...
2022-12-12 07:04:11,899 bleak.backends.winrt.client DEBUG: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x043D9F20>, error: BluetoothError.SUCCESS, status: GattSessionStatus.ACTIVE
Connected: True
2022-12-12 07:04:11,946 bleak.backends.winrt.client DEBUG: Disconnecting from BLE device...
2022-12-12 07:04:12,446 bleak.backends.winrt.client DEBUG: max_pdu_size_changed_handler: 517
2022-12-12 07:04:15,356 bleak.backends.winrt.client DEBUG: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x043D9F50>, error: BluetoothError.SUCCESS, status: GattSessionStatus.CLOSED
2022-12-12 07:04:15,356 bleak.backends.winrt.client DEBUG: max_pdu_size_changed_handler: 23
2022-12-12 07:04:15,356 bleak.backends.winrt.client DEBUG: closing requester
2022-12-12 07:04:15,356 bleak.backends.winrt.client DEBUG: closing session
Traceback (most recent call last):
  File "C:/Users/MyName/PycharmProjects/testBle/main.py", line 1, in <module>
    import ble_connection
  File "C:\Users\MyName\PycharmProjects\testBle\ble_connection.py", line 30, in <module>
    asyncio.run(connectAndReceiveData())
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\MyName\PycharmProjects\testBle\ble_connection.py", line 19, in connectAndReceiveData
    await client.start_notify(BOARD_STATE_CHARACTERISTIC_UUID, callback=newBoardStateReceived)
  File "D:\Python Projects 2022\testBle\lib\site-packages\bleak\__init__.py", line 649, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "D:\Python Projects 2022\testBle\lib\site-packages\bleak\backends\winrt\client.py", line 891, in start_notify
    cccd
OSError: [WinError -2140864509] The attribute cannot be written
```

here's the log from wireshark aswell
[captured packets.zip](https://github.com/hbldh/bleak/files/10205127/captured.packets.zip)

**Comment by dlech** [comment]
It looks like Windows might be using cached services for that device. So try setting the `winrt`, `used_cached_services` to `False`.

**Comment by olt96** [comment]
I tried setting this with: 
`
bleak.backends.winrt.client.WinRTClientArgs.use_cached_services = False`
in the beginning of the code but I still get the same error. 
Am I doing this right ?

**Comment by dlech** [comment]
Nope. Its a constructor arg for `BleakClient`.

```python
BleakClient(..., winrt=dict(use_cached_services=False))...
```

**Comment by olt96** [comment]
this seems to work fine. Thank you!

**Comment by alexanderturner** [comment]
Appear to be having the same issues on MacOS

**Comment by julienroulle** [comment]
Hi,

I am facing the same issue on Windows 11, bleak 0.21.1, python 3.11.6

The error message is as follow:
```
File "\.venv\Lib\site-packages\bleak\backends\winrt\client.py", line 974, in start_notify
await winrt_char.write_client_characteristic_configuration_descriptor_async(
OSError: [WinError -2140864509] The attribute cannot be written
```

I've tested with the above code, and I get the same error. I've tried the solution provided, on @olt96's code, and got the same output.

I'll continue searching, but if you have any idea, let me know :)
Thanks
