### ISSUE TITLE
Bleak fails to connect to Arduino BLE device 

### ISSUE THREAD

**Issue by ChrisUustal** [hbldh/bleak#1218]
* bleak version: 0.19.5
* Python version: 3.10.1
* Operating System: Windows 11 Build 22621.1105
* BlueZ version (`bluetoothctl -v`) in case of Linux: n/a

### Preface
If this question is better suited for the Arduino BLE issues tracker than the Bleak tracker, please let me know and I'm happy to take my issues there. I'm not sure which is the root cause of the issue right now, so any assistance would be appreciated, thanks! 

### Description

Hello, I am trying to implement a wearable device using an nRF52840 core which I can connect to my laptop via BLE for data logging. The particular microcontroller I am using is the Seeed Studio Xiao nRF52840 Sense. I am using some very lightly modified code based on the Arduino BLE examples, and I am currently trying to make one characteristic available which contains a float. This float is an accelerometer reading as part of an accelerometer service, not that it's particularly relevant. 

The issue I am seeing is that, while on my phone I can connect to the device using the nRF Connect app and read the characteristic data I want, I am not able to connect to it on my laptop using bleak where I would actually like to perform my wireless data collection. In particular, any code that I run which tries to connect to the device fails due to "TimeoutError". I used bleak without issue a few months ago on the same laptop with a different microcontroller + Arduino library and had no issues connecting + reading characteristics. See exact code + errors below. 

### What I Did

I tried using some of the example bleak files and those didn't work, so I stripped it down to the simplest possible file and it still returns the same error. File: 
```
import asyncio
from bleak import BleakClient

address = "83:C5:A2:61:D4:AD"

async def main(address):
    async with BleakClient(address) as client:
        client.get_services()

asyncio.run(main(address))
```
The error I get: 
```
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 402, in connect
    _, pending = await asyncio.wait(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\chris\Documents\School\Senior\EE435\Final Project\uBit\python\ble_test.py", line 10, in <module>
    asyncio.run(main(address))
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "c:\Users\chris\Documents\School\Senior\EE435\Final Project\uBit\python\ble_test.py", line 7, in main
    async with BleakClient(address) as client:
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\__init__.py", line 433, in __aenter__
    await self.connect()
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\__init__.py", line 471, in connect
    return await self._backend.connect(**kwargs)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 389, in connect
    async with async_timeout.timeout(timeout):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\async_timeout\__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\async_timeout\__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

I know it's generally recommended to make this as peripheral-agnostic as possible, but I'm not sure if things not working is because of Bleak, Arduino, or my own stupidity currently. Regardless, here is most of the Arduino code that matters (written and compiled in VSCode - Platform IO extension w/ some small mods to support the Xiao nRF52840 Sense): 
```
/*~~~~~~~~~~INCLUDES~~~~~~~~~~*/
#include <Arduino.h>
#include "imu.h"
#include "virtualTimer.h"
#include <ArduinoBLE.h>

/*~~~~~~~~~~DEFINES~~~~~~~~~~*/
#define SERIAL_SPEED 115200

/*~~~~~~~~~~VARIABLES~~~~~~~~~~*/
IMU imu(I2C_MODE, 0x6A);

VirtualTimerGroup timerGroup;

BLEService accelService("98867650-a908-4504-bfb1-770959c3776e");
BLEFloatCharacteristic accelXChar("98867651-a908-4504-bfb1-770959c3776e", BLERead | BLEWrite);

/*~~~~~~~~~~MEMBER FUNCTIONS~~~~~~~~~~*/
void imu_task_10ms();

void haptic_setup();

void ble_setup();
void ble_task_10ms();

/*~~~~~~~~~~MAIN~~~~~~~~~~*/
void setup()
{
  Serial.begin(SERIAL_SPEED);

  imu.imu.begin();
  haptic_setup();
  ble_setup();

  timerGroup.AddTimer(1000U, imu_task_10ms);
  timerGroup.AddTimer(1000U, ble_task_10ms);
}

void loop()
{
  timerGroup.Tick(millis());
}

/*~~~~~~~~~~PRIVATE FUNCTIONS~~~~~~~~~~*/
void imu_task_10ms()
{
  imu.read_accel();
  imu.read_gyro();
  imu.read_temp();

  // Serial.println(imu.accel.x);
}

void haptic_setup()
{
  pinMode(10, OUTPUT);
  digitalWrite(10, LOW);
}

void ble_setup()
{
  BLE.begin();
  BLE.setLocalName("uBitLongName");
  BLE.setAdvertisedService(accelService);
  accelService.addCharacteristic(accelXChar);
  BLE.addService(accelService);
  accelXChar.writeValue(0.0);
  BLE.advertise();
}

void ble_task_10ms()
{
  delay(5);
  BLEDevice central = BLE.central();

  if(central.connected())
  {
    Serial.print("Connected to ");
    Serial.println(central.deviceName());
    Serial.println("Writing Accel Value:");
    Serial.println(imu.accel.x);
    accelXChar.writeValue(imu.accel.x);
  }
  else
  {
    Serial.println("Not Connected");
  }
  
}
```

### Logs

Here are the full logs: 
```
2023-02-12 19:55:52,329 bleak.backends.winrt.scanner DEBUG: Received 86:2A:FD:3F:F5:DA: .
2023-02-12 19:55:52,329 bleak.backends.winrt.scanner DEBUG: skipping callback, waiting for scan response
2023-02-12 19:55:52,337 bleak.backends.winrt.scanner DEBUG: Received 30:09:20:10:76:8A: KS03-3930FC.
2023-02-12 19:55:52,337 bleak.backends.winrt.scanner DEBUG: skipping callback, waiting for scan response
2023-02-12 19:55:52,905 bleak.backends.winrt.scanner DEBUG: Received 18:87:58:AF:A7:A4: .
2023-02-12 19:55:52,921 bleak.backends.winrt.scanner DEBUG: Received 30:09:20:10:76:8A: KS03-3930FC.
2023-02-12 19:55:52,921 bleak.backends.winrt.scanner DEBUG: skipping callback, waiting for scan response
2023-02-12 19:55:53,027 bleak.backends.winrt.scanner DEBUG: Received 30:09:20:12:EE:C9: KS03-393227.
2023-02-12 19:55:53,027 bleak.backends.winrt.scanner DEBUG: skipping callback, waiting for scan response
2023-02-12 19:55:53,148 bleak.backends.winrt.scanner DEBUG: Received 83:C5:A2:61:D4:AD: .
2023-02-12 19:55:53,148 bleak.backends.winrt.scanner DEBUG: skipping callback, waiting for scan response
2023-02-12 19:55:53,148 bleak.backends.winrt.scanner DEBUG: Received 83:C5:A2:61:D4:AD: uBitLongName.
2023-02-12 19:55:53,148 bleak.backends.winrt.scanner DEBUG: 2 devices found. Watcher status: 3.
2023-02-12 19:55:53,148 bleak.backends.winrt.client DEBUG: Connecting to BLE device @ 83:C5:A2:61:D4:AD
2023-02-12 19:55:53,236 bleak.backends.winrt.client DEBUG: getting services (service_cache_mode=None, cache_mode=None)...
2023-02-12 19:55:53,348 bleak.backends.winrt.client DEBUG: session_status_changed_event_handler: id: <_bleak_winrt_Windows_Devices_Bluetooth.BluetoothDeviceId object at 0x00000256B84C1E70>, error: BluetoothError.SUCCESS, status: GattSessionStatus.ACTIVE
2023-02-12 19:55:53,412 bleak.backends.winrt.client DEBUG: max_pdu_size_changed_handler: 247
2023-02-12 19:55:55,488 bleak.backends.winrt.client DEBUG: 83:C5:A2:61:D4:AD: services changed
2023-02-12 19:55:55,488 bleak.backends.winrt.client DEBUG: 83:C5:A2:61:D4:AD: restarting get services due to services changed event
2023-02-12 19:55:55,488 bleak.backends.winrt.client DEBUG: getting services (service_cache_mode=<BluetoothCacheMode.CACHED: 0>, cache_mode=None)...    
2023-02-12 19:56:03,244 bleak.backends.winrt.client DEBUG: closing requester
2023-02-12 19:56:03,248 bleak.backends.winrt.client DEBUG: closing session
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 402, in connect
    _, pending = await asyncio.wait(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\chris\Documents\School\Senior\EE435\Final Project\uBit\python\ble_test.py", line 10, in <module>
    asyncio.run(main(address))
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "c:\Users\chris\Documents\School\Senior\EE435\Final Project\uBit\python\ble_test.py", line 7, in main
    async with BleakClient(address) as client:
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\__init__.py", line 433, in __aenter__
    await self.connect()
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\__init__.py", line 471, in connect
    return await self._backend.connect(**kwargs)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\bleak\backends\winrt\client.py", line 389, in connect
    async with async_timeout.timeout(timeout):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\async_timeout\__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\async_timeout\__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

**Comment by dlech** [comment]
Possibly fixed by #1143.
