### ISSUE TITLE
Scanner periodically crashes on Windows

### ISSUE THREAD

**Issue by vmacari** [hbldh/bleak#1330]
* bleak version:
    * bleak==0.20.2       
     * bleak-winrt==1.2.0 
* Python version: Python 3.11.3 
* Operating System: Windows 10
* BlueZ version (`bluetoothctl -v`) in case of Linux: ? 

### Description
    Scanning for devices

### What I Did

`self.devices = await BleakScanner.discover()`

### Logs
```

handle: <Handle BleakScannerWinRT._stopped_handler(<_bleak_winrt...002092A07A7F0>, <_bleak_winrt...002092A0EA710>)>
Traceback (most recent call last):
  File "...asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "...\site-packages\bleak\backends\winrt\scanner.py", line 213, in _stopped_handler
    len(self.seen_devices), self.watcher.status
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status'
```

**Comment by vmacari** [comment]
Added a pull request https://github.com/hbldh/bleak/pull/1331
