### ISSUE TITLE
examples/service_explorer.py errors out with "bleak.exc.BleakDBusError: [org.bluez.Error.Failed] br-connection-unknown"

### ISSUE THREAD

**Issue by jsmif** [hbldh/bleak#1333]
* bleak version: bleak-0.21.0a1 (but the same error occurs if I checkout and install bleak-0.20.2)
* Python version: Python 3.10.6 & 3.10.11
* Operating System: Ubuntu 22.04 (two different systems)
* BlueZ version (`bluetoothctl -v`) in case of Linux: bluetoothctl: 5.64 (both systems)

### Description

Trying to scan GATT and see available characteristics.

Installed with
```
git clone https://github.com/hbldh/bleak.git
cd bleak
pip3 install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/user/Downloads/bleak
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: async-timeout<5,>=3.0.0 in /home/user/.local/lib/python3.10/site-packages (from bleak==0.21.0a1) (4.0.2)
Requirement already satisfied: dbus-fast<2.0.0,>=1.83.0 in /home/user/.local/lib/python3.10/site-packages (from bleak==0.21.0a1) (1.86.0)
Building wheels for collected packages: bleak
  Building editable for bleak (pyproject.toml) ... done
  Created wheel for bleak: filename=bleak-0.21.0a1-py3-none-any.whl size=3413 sha256=44674f94c6a828ede3bc84712d7642f6f1e99465784d2bcb6fac2c7e9073bc52
  Stored in directory: /tmp/pip-ephem-wheel-cache-0py9upgz/wheels/d4/3b/06/13cf45a652a54e73f849d6ff9a18603cdf3145a3e31f1ddfc4
Successfully built bleak
Installing collected packages: bleak
  Attempting uninstall: bleak
    Found existing installation: bleak 0.20.2
    Uninstalling bleak-0.20.2:
      Successfully uninstalled bleak-0.20.2
Successfully installed bleak-0.21.0a1
```

### What I Did

```
 python3 ./service_explorer.py --address 6C:<CENSORED>
2023-06-14 12:16:02,343 __main__ INFO: starting scan...
2023-06-14 12:16:02,649 __main__ INFO: connecting to device...
Traceback (most recent call last):
  File "/home/user/Downloads/bleak/examples/./service_explorer.py", line 129, in <module>
    asyncio.run(main(args))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/Downloads/bleak/examples/./service_explorer.py", line 41, in main
    async with BleakClient(
  File "/home/user/Downloads/bleak/bleak/__init__.py", line 491, in __aenter__
    await self.connect()
  File "/home/user/Downloads/bleak/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
  File "/home/user/Downloads/bleak/bleak/backends/bluezdbus/client.py", line 244, in connect
    assert_reply(reply)
  File "/home/user/Downloads/bleak/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] br-connection-unknown
```
### Logs

Unfortunately I can't provide logs as that would provide my exact physical location... Please just see if this replicates for you on Ubuntu 22.04

**Comment by dlech** [comment]
Same answer as your other issues - it is not really possible to determine what is going on without seeing Bluetooth packet logs.

**Comment by dlech** [comment]
> Is it possible to query without connecting through bleak?

No, it is not. This is a limitation of BlueZ (`bluetoothd`) and the D-Bus API as you have seen with `bluetoothctl`.
