### ISSUE TITLE
Error in example in https://bleak.readthedocs.io/en/latest/troubleshooting.html

### ISSUE THREAD

**Issue by jsmif** [hbldh/bleak#1334]
* bleak version: bleak-0.21.0a1
* Python version: Python 3.10.6
* Operating System: Ubuntu 22.04
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.64

### Description

Just pointing out an error in the documentation

### What I Did

Copied the following code from https://bleak.readthedocs.io/en/latest/troubleshooting.html into test.py

```
import asyncio
from typing import Sequence

from bleak import BleakClient, BleakScanner
from bleak.backends.device import BLEDevice


async def find_all_devices_services()
    scanner = BleakScanner()
    devices: Sequence[BLEDevice] = scanner.discover(timeout=5.0)
    for d in devices:
        async with BleakClient(d) as client:
            print(client.services)


asyncio.run(find_all_devices_services())
```
The first error was

```
 python3 test.py 
  File "/home/user/Downloads/bleak/examples/test.py", line 8
    async def find_all_devices_services()
                                         ^
SyntaxError: expected ':'
```

Once corrected by adding a :, I got the error:

```
 python3 test.py 
Traceback (most recent call last):
  File "/home/user/Downloads/bleak/examples/test.py", line 16, in <module>
    asyncio.run(find_all_devices_services())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/Downloads/bleak/examples/test.py", line 11, in find_all_devices_services
    for d in devices:
TypeError: 'coroutine' object is not iterable
sys:1: RuntimeWarning: coroutine 'BleakScanner.discover' was never awaited
```

**Comment by pymenow** [comment]
@dlech do you have an estimate on when the next bleak release will happen ? My package depends on fixes that are in the develop branch .

**Comment by dlech** [comment]
No ETA, but I've been trying to do quarterly releases, so we are due for one soon.
