### ISSUE TITLE
ValueError('badly formed hexadecimal UUID string') when using BleakScanner.discover()

### ISSUE THREAD

**Issue by itsbeenemotional** [hbldh/bleak#1362]
* bleak version: 0.20.2
* Python version: 3.11.4
* Operating System: macOS 13.4.1

### Description

I have previously (as recently as last week) used bleak on my MacBook without issues. However, today it suddenly started throwing `ValueError('badly formed hexadecimal UUID string')` when running scripts that previously worked just fine.

To trouble shoot, I tried to run this minimal device discovery script (found [here](https://github.com/hbldh/bleak#usage)):

```
import asyncio
from bleak import BleakScanner

async def main():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d)

asyncio.run(main())
```

I received the following error message:

```
Exception in callback CentralManagerDelegate.did_discover_peripheral(<CBCentralMan...: 0x11007db10>, <CBPeripheral... disconnected>, {
    kCBAdvD...21.3558871";
}, -93)
handle: <Handle CentralManagerDelegate.did_discover_peripheral(<CBCentralMan...: 0x11007db10>, <CBPeripheral... disconnected>, {
    kCBAdvD...21.3558871";
}, -93)>
Traceback (most recent call last):
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/CentralManagerDelegate.py", line 265, in did_discover_peripheral
    callback(peripheral, advertisementData, RSSI)
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/scanner.py", line 116, in callback
    service_uuids = [
                    ^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/scanner.py", line 117, in <listcomp>
    cb_uuid_to_str(u) for u in a.get("kCBAdvDataServiceUUIDs", [])
    ^^^^^^^^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/utils.py", line 19, in cb_uuid_to_str
    return normalize_uuid_str(uuid.UUIDString())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/uuids.py", line 1167, in normalize_uuid_str
    return str(UUID(uuid))
               ^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
Exception in callback CentralManagerDelegate.did_discover_peripheral(<CBCentralMan...: 0x11007db10>, <CBPeripheral... disconnected>, {
    kCBAdvD...321.355904";
}, -92)
handle: <Handle CentralManagerDelegate.did_discover_peripheral(<CBCentralMan...: 0x11007db10>, <CBPeripheral... disconnected>, {
    kCBAdvD...321.355904";
}, -92)>
Traceback (most recent call last):
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/CentralManagerDelegate.py", line 265, in did_discover_peripheral
    callback(peripheral, advertisementData, RSSI)
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/scanner.py", line 116, in callback
    service_uuids = [
                    ^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/scanner.py", line 117, in <listcomp>
    cb_uuid_to_str(u) for u in a.get("kCBAdvDataServiceUUIDs", [])
    ^^^^^^^^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/utils.py", line 19, in cb_uuid_to_str
    return normalize_uuid_str(uuid.UUIDString())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/uuids.py", line 1167, in normalize_uuid_str
    return str(UUID(uuid))
               ^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
Exception in callback CentralManagerDelegate.did_discover_peripheral(<CBCentralMan...: 0x11007db10>, <CBPeripheral... disconnected>, {
    kCBAdvD...22.5353841";
}, -63)
handle: <Handle CentralManagerDelegate.did_discover_peripheral(<CBCentralMan...: 0x11007db10>, <CBPeripheral... disconnected>, {
    kCBAdvD...22.5353841";
}, -63)>
Traceback (most recent call last):
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/CentralManagerDelegate.py", line 265, in did_discover_peripheral
    callback(peripheral, advertisementData, RSSI)
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/scanner.py", line 116, in callback
    service_uuids = [
                    ^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/scanner.py", line 117, in <listcomp>
    cb_uuid_to_str(u) for u in a.get("kCBAdvDataServiceUUIDs", [])
    ^^^^^^^^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/utils.py", line 19, in cb_uuid_to_str
    return normalize_uuid_str(uuid.UUIDString())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/uuids.py", line 1167, in normalize_uuid_str
    return str(UUID(uuid))
               ^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
Exception in callback CentralManagerDelegate.did_discover_peripheral(<CBCentralMan...: 0x11007db10>, <CBPeripheral... disconnected>, {
    kCBAdvD...22.5365551";
}, -61)
handle: <Handle CentralManagerDelegate.did_discover_peripheral(<CBCentralMan...: 0x11007db10>, <CBPeripheral... disconnected>, {
    kCBAdvD...22.5365551";
}, -61)>
Traceback (most recent call last):
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/CentralManagerDelegate.py", line 265, in did_discover_peripheral
    callback(peripheral, advertisementData, RSSI)
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/scanner.py", line 116, in callback
    service_uuids = [
                    ^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/scanner.py", line 117, in <listcomp>
    cb_uuid_to_str(u) for u in a.get("kCBAdvDataServiceUUIDs", [])
    ^^^^^^^^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/backends/corebluetooth/utils.py", line 19, in cb_uuid_to_str
    return normalize_uuid_str(uuid.UUIDString())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/site-packages/bleak/uuids.py", line 1167, in normalize_uuid_str
    return str(UUID(uuid))
               ^^^^^^^^^^
  File "/Users/username/miniconda3/envs/myenv/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```
Please advise. Thanks!

**Comment by dlech** [comment]
Is this still a problem if you use the develop branch?
