### ISSUE TITLE
BleakClient returns badly formed hexadecimal UUID string

### ISSUE THREAD

**Issue by Odud** [hbldh/bleak#1431]
* bleak version: 0.21.1
* Python version: 3.11.4
* Operating System: Raspbian GNU/Linux 12 (bookworm)
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.66

### Description

I am trying to retrieve details of a particular service using the services parameter of BleakClient. Pretty new to all of this so apologies in advance if I am doing something stupid.

### What I Did

I formed what I hoped was the UUID using:

```
service = uuids.normalize_uuid_16(0x180a)
logger.info("Service %s", service)
# INFO: Service 0000180a-0000-1000-8000-00805f9b34fb
```

and then passed service to BleakClient

```
try:
    async with BleakClient(
                    d, timeout=60, services=service
    ) as client:
....
except Exception as e:
    logger.error(" BleakClient [Device] %s, Error: %s", d, e)
# ERROR:  BleakClient [Device] A4:C1:38:59:F1:E6: GVH5075_F1E6, Error: badly formed hexadecimal UUID string
```

### Logs

I turned on logging, there was a mass of output related to the discover process, not shown in the snippet above, but nothin produced during the BleakClient call.

**Comment by dlech** [comment]
What is the stack trace of the error?

**Comment by Odud** [comment]
Stack trace as requested

```
INFO: Service 0000180a-0000-1000-8000-00805f9b34fb
Traceback (most recent call last):
  File "/home/production/Bleak/discover_explore.py", line 88, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/production/Bleak/discover_explore.py", line 26, in main
    async with BleakClient(
               ^^^^^^^^^^^^
  File "/home/production/.venv/lib/python3.11/site-packages/bleak/__init__.py", line 528, in __init__
    else set(map(normalize_uuid_str, services)),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/production/.venv/lib/python3.11/site-packages/bleak/uuids.py", line 1187, in normalize_uuid_str
    return str(UUID(uuid))
               ^^^^^^^^^^
  File "/usr/local/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```

**Comment by Odud** [comment]
That's fixed it thanks. VSCode was telling me it expected a string...

Thanks for your rapid help.

Pete Barlow

**Comment by dlech** [comment]
The type hint looks correct to me:

https://github.com/hbldh/bleak/blob/42797edb99534e5558433deca29fdc08574ceae8/bleak/__init__.py#L510
