### ISSUE TITLE
Timeout Error in Windows10

### ISSUE THREAD

**Issue by MrTree302** [hbldh/bleak#1442]
* bleak version: 0.21.1
* Python version: 3.12.0
* Operating System: Windows10 22H2 19045.3570
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

I try to search the MAC address of an Arduino BLE device and connect to it. The scanner works fine and find my device, but when  trying to connect to the device, the process gets stuck. After several minutes, it shows timeout error.

### What I Did

When timeout set to 60, the log shows timeout error. But when I adjust it to 200, the log shows OSError.
This is my code.
```
async def main():
    print("starting scan...")

    #find device based on MAC
    device = await BleakScanner.find_device_by_address(
        par_device_addr, cb=dict(use_bdaddr=False)  
    )
    if device is None:
        print("could not find device with address '%s'", par_device_addr)
        return

    print("connecting to device...")
    async with BleakClient(device,timeout=60.0) as client:
        print("Connected")
        await client.start_notify(par_notification_characteristic, notification_handler)        
        await asyncio.sleep(10.0)   
        await client.stop_notify(par_notification_characteristic)
```

### Logs
When timeout = 60
```
starting scan...
connecting to device...
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 480, in connect    
    self.services = await self.get_services(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 713, in get_services
    await FutureLike(self._requester.get_gatt_services_async(*srv_args)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 1122, in __await__ 
    yield self  # This tells Task to wait for completion.       
    ^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 1065, in result    
    raise asyncio.CancelledErrorasyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\edge_computing\test\ble_test.py", line 33, in <module>     
    asyncio.run(main())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run  
    return runner.run(main)     
           ^^^^^^^^^^^^^^^^     
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run  
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()      
           ^^^^^^^^^^^^^^^      
  File "E:\edge_computing\test\ble_test.py", line 27, in main
    async with BleakClient(device,timeout=30.0) as client:      
  File "C:\Python312\Lib\site-packages\bleak\__init__.py", line 
565, in __aenter__
    await self.connect()        
  File "C:\Python312\Lib\site-packages\bleak\__init__.py", line 
605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 436, in connect    
    async with async_timeout(timeout):
  File "C:\Python312\Lib\asyncio\timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```
When timeout = 200
```
starting scan...
connecting to device...
Traceback (most recent call last):
  File "E:\edge_computing\test\ble_test.py", line 33, in <module>     
    asyncio.run(main())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run  
    return runner.run(main)     
           ^^^^^^^^^^^^^^^^     
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run  
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()      
           ^^^^^^^^^^^^^^^      
  File "E:\edge_computing\test\ble_test.py", line 27, in main
    async with BleakClient(device,timeout=200.0) as client:     
  File "C:\Python312\Lib\site-packages\bleak\__init__.py", line 
565, in __aenter__
    await self.connect()
  File "C:\Python312\Lib\site-packages\bleak\__init__.py", 
line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 480, in connect
    self.services = await self.get_services(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 713, in get_services
    await FutureLike(self._requester.get_gatt_services_async(*srv_args)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 1122, in __await__
    yield self  # This tells Task to wait for completion.  
    ^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 1072, in result
    raise WinError(error_code)
OSError: [WinError -2147418113] Disaster Error
```
[wireshark_log.zip](https://github.com/hbldh/bleak/files/13060161/wireshark_log.zip)

**Comment by MrTree302** [comment]
Oh, I find the reason why my device can't be connected. There is nothing wrong with my receiver (python code, WinRT backend) but with ArduinoBLE library. When I upgrade it from 1.1.0 version to 1.3.6 version, my device can be connected normally.
