### ISSUE TITLE
BleakClient can not run on RISC-V linux

### ISSUE THREAD

**Issue by mcpanl** [hbldh/bleak#1657]
* bleak version: 0.22.3
* Python version: 3.11
* Operating System: RISC-V
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.6.8

### Description
![image](https://github.com/user-attachments/assets/1e1c6097-0296-4848-a89a-e86ea13f008e)

The following code can run normally on the Windows platform, but it cannot run on Linux development boards on the RISC-V platform.

![image](https://github.com/user-attachments/assets/e8dce175-b81b-4e9c-980d-cba23eefcf84)

### What I Did
1. get a linux borard (Sipeed LicheeRV Nano)
[https://www.alibaba.com/product-detail/Sipeed-LicheeRV-Nano-Litchi-Pi-SG2002_1601059587927.html?spm=a2700.galleryofferlist.normal_offer.d_title.59f213a0npUk9B](https://www.alibaba.com/product-detail/Sipeed-LicheeRV-Nano-Litchi-Pi-SG2002_1601059587927.html?spm=a2700.galleryofferlist.normal_offer.d_title.59f213a0npUk9B)

wiki: [https://wiki.sipeed.com/maixpy/en/index.html](https://wiki.sipeed.com/maixpy/en/index.html)

2. pip install bleak

3. create hci with /dev/ttyS1 and up it.
![29054-4eb7ba9fc3714363ae213f91209c0b5f](https://github.com/user-attachments/assets/3cbc4638-15d3-4402-8457-a9e30b10786f)
![29054-11ea08af61344ce79e332ec016034dcf](https://github.com/user-attachments/assets/ecfb08f6-d357-47f8-93c3-9fa1f85588a3)

4. run above-mentioned test code

``` python
import asyncio
from bleak import BleakScanner, BleakClient

async def main():
    device = await BleakScanner.find_device_by_address(
            'F6:0C:C0:F5:66:52'
        )

    print(device)

    if device is None:
        print('not found device')
        return

    async with BleakClient(device) as client:
        print('connected')
        print(client)

asyncio.run(main())
```

### Logs
```
F6:0C:C0:F5:66:52: NRF_BATTERY_01
Traceback (most recent call last):
  File "src/dbus_fast/_private/unmarshaller.py", line 301, in dbus_fast._private.unmarshaller.Unmarshaller._read_sock_with_fds
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

BlockingIOError
Exception ignored in: 'dbus_fast._private.unmarshaller.Unmarshaller._read_sock_with_fds'
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
BlockingIOError: 
```

**Comment by mcpanl** [comment]
this is full logs
```
# btmon 
Bluetooth monitor ver 5.68
= Note: Linux version 5.10.4-tag- (riscv64)                                                0.708175
= Note: Bluetooth subsystem version 2.22                                                   0.708186
= New Index: C4:3C:B0:6D:53:BD (Primary,UART,hci0)                                  [hci0] 0.708190
= Open Index: C4:3C:B0:6D:53:BD                                                     [hci0] 0.708193
= Index Info: C4:3C:B0:6D:53:BD (RivieraWaves S.A.S)                                [hci0] 0.708198
@ MGMT Open: bluetoothd (privileged) version 1.18                                 {0x0001} 0.708202


@ MGMT Command: Start Service Discovery (0x003a) plen 4                   {0x0001} [hci0] 22.810137
        Address type: 0x06
          LE Public
          LE Random
        RSSI: invalid (0x7f)
        UUIDs: 0
< HCI Command: LE Set Random Address (0x08|0x0005) plen 6                       #1 [hci0] 22.811904
        Address: 3D:31:BA:07:FD:92 (Non-Resolvable)
> HCI Event: Command Complete (0x0e) plen 4                                     #2 [hci0] 22.812883
      LE Set Random Address (0x08|0x0005) ncmd 5
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Parameters (0x08|0x0041) plen 8             #3 [hci0] 22.812987
        Own address type: Random (0x01)
        Filter policy: Accept all advertisement (0x00)
        PHYs: 0x01
        Entry 0: LE 1M
          Type: Active (0x01)
          Interval: 11.250 msec (0x0012)
          Window: 11.250 msec (0x0012)
> HCI Event: Command Complete (0x0e) plen 4                                     #4 [hci0] 22.813647
      LE Set Extended Scan Parameters (0x08|0x0041) ncmd 5
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                 #5 [hci0] 22.813707
        Extended scan: Enabled (0x01)
        Filter duplicates: Enabled (0x01)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                     #6 [hci0] 22.814640
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 5
        Status: Success (0x00)
@ MGMT Event: Command Complete (0x0001) plen 4                            {0x0001} [hci0] 22.814764
      Start Service Discovery (0x003a) plen 1
        Status: Success (0x00)
        Address type: 0x06
          LE Public
          LE Random
@ MGMT Event: Discovering (0x0013) plen 2                                 {0x0001} [hci0] 22.814786
        Address type: 0x06
          LE Public
          LE Random
        Discovery: Enabled (0x01)
> HCI Event: LE Meta Event (0x3e) plen 28                                       #7 [hci0] 22.824706
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Random (0x01)
        Address: 54:B0:00:9A:91:70 (Resolvable)
        Data length: 16
        TX power: -9 dBm
        Service Data: Google (0xfe2c)
          Data: 003000000011b41464
        RSSI: -83 dBm (0xad)
> HCI Event: LE Meta Event (0x3e) plen 28                                       #8 [hci0] 22.825432
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Scan response - SCAN_RSP (0x04)
        Address type: Random (0x01)
        Address: 54:B0:00:9A:91:70 (Resolvable)
        Data length: 16
        Name (complete): ACTON III [LE]
        RSSI: -84 dBm (0xac)
@ MGMT Event: Device Found (0x0012) plen 46                               {0x0001} [hci0] 22.828137
        LE Address: 54:B0:00:9A:91:70 (Resolvable)
        RSSI: -84 dBm (0xac)
        Flags: 0x00000000
        Data length: 32
        TX power: -9 dBm
        Service Data: Google (0xfe2c)
          Data: 003000000011b41464
        Name (complete): ACTON III [LE]
> HCI Event: LE Meta Event (0x3e) plen 32                                       #9 [hci0] 22.831819
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Random (0x01)
        Address: C0:C6:5B:9D:20:64 (Static)
        Data length: 20
        Flags: 0x04
          BR/EDR Not Supported
        Company: Zound Industries International AB (1626)
          Data: 0800505e5c6bc61400
        16-bit Service UUIDs (partial): 1 entry
          Unknown (0xaa00)
        RSSI: -84 dBm (0xac)
> HCI Event: LE Meta Event (0x3e) plen 28                                      #10 [hci0] 22.833748
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Scan response - SCAN_RSP (0x04)
        Address type: Random (0x01)
        Address: C0:C6:5B:9D:20:64 (Static)
        Data length: 16
        Name (complete): ACTON III [LE]
        RSSI: -83 dBm (0xad)
@ MGMT Event: Device Found (0x0012) plen 50                               {0x0001} [hci0] 22.834270
        LE Address: C0:C6:5B:9D:20:64 (Static)
        RSSI: -83 dBm (0xad)
        Flags: 0x00000000
        Data length: 36
        Flags: 0x04
          BR/EDR Not Supported
        Company: Zound Industries International AB (1626)
          Data: 0800505e5c6bc61400
        16-bit Service UUIDs (partial): 1 entry
          Unknown (0xaa00)
        Name (complete): ACTON III [LE]
> HCI Event: LE Meta Event (0x3e) plen 30                                      #11 [hci0] 22.841379
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Public (0x00)
        Address: 04:CD:15:2A:8C:B6 (Silicon Laboratories)
        Data length: 18
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        Service Data: Xiaomi Inc. (0xfe95)
          Data: 1055641bc1b68c2a15cd04
        RSSI: -90 dBm (0xa6)
> HCI Event: LE Meta Event (0x3e) plen 12                                      #12 [hci0] 22.842058
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Scan response - SCAN_RSP (0x04)
        Address type: Public (0x00)
        Address: 04:CD:15:2A:8C:B6 (Silicon Laboratories)
        Data length: 0
        RSSI: 1 dBm (0x01)
@ MGMT Event: Device Found (0x0012) plen 32                               {0x0001} [hci0] 22.842126
        LE Address: 04:CD:15:2A:8C:B6 (Silicon Laboratories)
        RSSI: 1 dBm (0x01)
        Flags: 0x00000000
        Data length: 18
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        Service Data: Xiaomi Inc. (0xfe95)
          Data: 1055641bc1b68c2a15cd04
> HCI Event: LE Meta Event (0x3e) plen 15                                      #13 [hci0] 22.845229
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Public (0x00)
        Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Data length: 3
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        RSSI: -47 dBm (0xd1)
> HCI Event: LE Meta Event (0x3e) plen 28                                      #14 [hci0] 22.846014
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Scan response - SCAN_RSP (0x04)
        Address type: Public (0x00)
        Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Data length: 16
        Name (complete): NRF_BATTERY_01
        RSSI: -47 dBm (0xd1)
@ MGMT Event: Device Found (0x0012) plen 33                               {0x0001} [hci0] 22.846061
        LE Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        RSSI: -47 dBm (0xd1)
        Flags: 0x00000000
        Data length: 19
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        Name (complete): NRF_BATTERY_01
@ MGMT Command: Stop Discovery (0x0024) plen 1                            {0x0001} [hci0] 22.865936
        Address type: 0x06
          LE Public
          LE Random
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                #15 [hci0] 22.866018
        Extended scan: Disabled (0x00)
        Filter duplicates: Disabled (0x00)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                    #16 [hci0] 22.867646
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 5
        Status: Success (0x00)
@ MGMT Event: Command Complete (0x0001) plen 4                            {0x0001} [hci0] 22.867728
      Stop Discovery (0x0024) plen 1
        Status: Success (0x00)
        Address type: 0x06
          LE Public
          LE Random
@ MGMT Event: Discovering (0x0013) plen 2                                 {0x0001} [hci0] 22.867752
        Address type: 0x06
          LE Public
          LE Random
        Discovery: Disabled (0x00)
< HCI Command: LE Set Extended Scan Parameters (0x08|0x0041) plen 8            #17 [hci0] 22.994765
        Own address type: Public (0x00)
        Filter policy: Ignore not in accept list (0x01)
        PHYs: 0x01
        Entry 0: LE 1M
          Type: Passive (0x00)
          Interval: 60.000 msec (0x0060)
          Window: 60.000 msec (0x0060)
> HCI Event: Command Complete (0x0e) plen 4                                    #18 [hci0] 22.995845
      LE Set Extended Scan Parameters (0x08|0x0041) ncmd 5
        Status: Success (0x00)
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                #19 [hci0] 22.995965
        Extended scan: Enabled (0x01)
        Filter duplicates: Enabled (0x01)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                    #20 [hci0] 22.996535
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 5
        Status: Success (0x00)
> HCI Event: LE Meta Event (0x3e) plen 15                                      #21 [hci0] 23.047680
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Public (0x00)
        Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Data length: 3
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        RSSI: -47 dBm (0xd1)
< HCI Command: LE Set Extended Scan Enable (0x08|0x0042) plen 6                #22 [hci0] 23.047762
        Extended scan: Disabled (0x00)
        Filter duplicates: Disabled (0x00)
        Duration: 0 msec (0x0000)
        Period: 0.00 sec (0x0000)
> HCI Event: Command Complete (0x0e) plen 4                                    #23 [hci0] 23.049088
      LE Set Extended Scan Enable (0x08|0x0042) ncmd 5
        Status: Success (0x00)
< HCI Command: LE Extended Create Connection (0x08|0x0043) plen 26             #24 [hci0] 23.049156
        Filter policy: Accept list is not used (0x00)
        Own address type: Public (0x00)
        Peer address type: Public (0x00)
        Peer address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Initiating PHYs: 0x01
        Entry 0: LE 1M
          Scan interval: 60.000 msec (0x0060)
          Scan window: 60.000 msec (0x0060)
          Min connection interval: 30.00 msec (0x0018)
          Max connection interval: 50.00 msec (0x0028)
          Connection latency: 0 (0x0000)
          Supervision timeout: 420 msec (0x002a)
          Min connection length: 0.000 msec (0x0000)
          Max connection length: 0.000 msec (0x0000)
> HCI Event: Command Status (0x0f) plen 4                                      #25 [hci0] 23.049695
      LE Extended Create Connection (0x08|0x0043) ncmd 5
        Status: Success (0x00)
> HCI Event: LE Meta Event (0x3e) plen 31                                      #26 [hci0] 23.149076
      LE Enhanced Connection Complete (0x0a)
        Status: Success (0x00)
        Handle: 7
        Role: Central (0x00)
        Peer address type: Public (0x00)
        Peer address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Local resolvable private address: 00:00:00:00:00:00 (Non-Resolvable)
        Peer resolvable private address: 00:00:00:00:00:00 (Non-Resolvable)
        Connection interval: 50.00 msec (0x0028)
        Connection latency: 0 (0x0000)
        Supervision timeout: 420 msec (0x002a)
        Central clock accuracy: 0x00
@ MGMT Event: Device Connected (0x000b) plen 16                           {0x0001} [hci0] 23.149132
        LE Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Flags: 0x00000000
        Data length: 3
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
< HCI Command: LE Read Remote Used Features (0x08|0x0016) plen 2               #27 [hci0] 23.149325
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
> HCI Event: LE Meta Event (0x3e) plen 4                                       #28 [hci0] 23.149900
      LE Channel Selection Algorithm (0x14)
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Algorithm: #1 (0x00)
> HCI Event: Command Status (0x0f) plen 4                                      #29 [hci0] 23.150706
      LE Read Remote Used Features (0x08|0x0016) ncmd 5
        Status: Success (0x00)
@ RAW Open: btmon (privileged) version 2.22                                      {0x0002} 23.158359
@ RAW Close: btmon                                                               {0x0002} 23.158396
> HCI Event: LE Meta Event (0x3e) plen 12                                      #30 [hci0] 23.244967
      LE Read Remote Used Features (0x04)
        Status: Success (0x00)
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Features: 0x0f 0x49 0x01 0x00 0x00 0x00 0x00 0x00
          LE Encryption
          Connection Parameter Request Procedure
          Extended Reject Indication
          Peripheral-initiated Features Exchange
          LE 2M PHY
          LE Coded PHY
          Channel Selection Algorithm #2
          Minimum Number of Used Channels Procedure
< ACL Data TX: Handle 7 flags 0x00 dlen 7                                      #31 [hci0] 23.252419
      ATT: Exchange MTU Request (0x02) len 2
        Client RX MTU: 517
> HCI Event: Number of Completed Packets (0x13) plen 5                         #32 [hci0] 23.294371
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 41 msec (41-41 msec ~41 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 7                                      #33 [hci0] 23.344380
      ATT: Exchange MTU Response (0x03) len 2
        Server RX MTU: 247
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #34 [hci0] 23.344796
      ATT: Read By Type Request (0x08) len 6
        Handle range: 0x0001-0xffff
        Attribute type: Server Supported Features (0x2b3a)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #35 [hci0] 23.394387
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (41-49 msec ~45 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 9                                      #36 [hci0] 23.544408
      ATT: Error Response (0x01) len 4
        Read By Type Request (0x08)
        Handle: 0x0001
        Error: Attribute Not Found (0x0a)
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #37 [hci0] 23.544785
      ATT: Read By Group Type Request (0x10) len 6
        Handle range: 0x0001-0xffff
        Attribute group type: Primary Service (0x2800)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #38 [hci0] 23.594404
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (41-49 msec ~47 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 18                                     #39 [hci0] 23.744549
      ATT: Read By Group Type Response (0x11) len 13
        Attribute data length: 6
        Attribute group list: 2 entries
        Handle range: 0x0001-0x0005
        UUID: Generic Access Profile (0x1800)
        Handle range: 0x0006-0x0009
        UUID: Generic Attribute Profile (0x1801)
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #40 [hci0] 23.744926
      ATT: Read By Group Type Request (0x10) len 6
        Handle range: 0x000a-0xffff
        Attribute group type: Primary Service (0x2800)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #41 [hci0] 23.794388
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (41-49 msec ~48 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 26                                     #42 [hci0] 23.944661
      ATT: Read By Group Type Response (0x11) len 21
        Attribute data length: 20
        Attribute group list: 1 entry
        Handle range: 0x000a-0x0010
        UUID: Vendor specific (19b10000-e8f2-537e-4f6c-d104768a1214)
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #43 [hci0] 23.945032
      ATT: Read By Group Type Request (0x10) len 6
        Handle range: 0x0011-0xffff
        Attribute group type: Primary Service (0x2800)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #44 [hci0] 23.994392
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (41-49 msec ~48 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 9                                      #45 [hci0] 24.144417
      ATT: Error Response (0x01) len 4
        Read By Group Type Request (0x10)
        Handle: 0x0011
        Error: Attribute Not Found (0x0a)
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #46 [hci0] 24.144905
      ATT: Read By Group Type Request (0x10) len 6
        Handle range: 0x0001-0xffff
        Attribute group type: Secondary Service (0x2801)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #47 [hci0] 24.194406
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (41-49 msec ~49 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 9                                      #48 [hci0] 24.344432
      ATT: Error Response (0x01) len 4
        Read By Group Type Request (0x10)
        Handle: 0x0001
        Error: Attribute Not Found (0x0a)
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #49 [hci0] 24.344811
      ATT: Read By Type Request (0x08) len 6
        Handle range: 0x0001-0x0010
        Attribute type: Include (0x2802)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #50 [hci0] 24.394394
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (41-49 msec ~49 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 9                                      #51 [hci0] 24.544415
      ATT: Error Response (0x01) len 4
        Read By Type Request (0x08)
        Handle: 0x0001
        Error: Attribute Not Found (0x0a)
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #52 [hci0] 24.544794
      ATT: Read By Type Request (0x08) len 6
        Handle range: 0x0001-0x0010
        Attribute type: Characteristic (0x2803)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #53 [hci0] 24.594386
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (41-49 msec ~49 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 27                                     #54 [hci0] 24.744637
      ATT: Read By Type Response (0x09) len 22
        Attribute data length: 7
        Attribute data list: 3 entries
        Handle: 0x0002
        Value: 020300002a
            Properties: 0x02
              Read (0x02)
            Value Handle: 0x0003
            Value UUID: Device Name (0x2a00)
        Handle: 0x0004
        Value: 020500012a
            Properties: 0x02
              Read (0x02)
            Value Handle: 0x0005
            Value UUID: Appearance (0x2a01)
        Handle: 0x0007
        Value: 200800052a
            Properties: 0x20
              Indicate (0x20)
            Value Handle: 0x0008
            Value UUID: Service Changed (0x2a05)
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #55 [hci0] 24.745009
      ATT: Read By Type Request (0x08) len 6
        Handle range: 0x0008-0x0010
        Attribute type: Characteristic (0x2803)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #56 [hci0] 24.794408
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (41-49 msec ~49 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 27                                     #57 [hci0] 24.944626
> ACL Data RX: Handle 7 flags 0x01 dlen 21                                     #58 [hci0] 24.945275
      ATT: Read By Type Response (0x09) len 43
        Attribute data length: 21
        Attribute data list: 2 entries
        Handle: 0x000b
        Value: 1a0c0014128a7604d16c4f7e53f2e80100b119
            Properties: 0x1a
              Read (0x02)
              Write (0x08)
              Notify (0x10)
            Value Handle: 0x000c
            Value UUID: Vendor specific (19b10001-e8f2-537e-4f6c-d104768a1214)
        Handle: 0x000e
        Value: 120f0014128a7604d16c4f7e53f2e80200b119
            Properties: 0x12
              Read (0x02)
              Notify (0x10)
            Value Handle: 0x000f
            Value UUID: Vendor specific (19b10002-e8f2-537e-4f6c-d104768a1214)
< ACL Data TX: Handle 7 flags 0x00 dlen 11                                     #59 [hci0] 24.945638
      ATT: Read By Type Request (0x08) len 6
        Handle range: 0x000f-0x0010
        Attribute type: Characteristic (0x2803)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #60 [hci0] 24.994393
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 48 msec (41-49 msec ~49 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 9                                      #61 [hci0] 25.144412
      ATT: Error Response (0x01) len 4
        Read By Type Request (0x08)
        Handle: 0x000f
        Error: Attribute Not Found (0x0a)
< ACL Data TX: Handle 7 flags 0x00 dlen 9                                      #62 [hci0] 25.172611
      ATT: Write Request (0x12) len 4
        Handle: 0x0009 Type: Client Characteristic Configuration (0x2902)
        Value Handle: 0x0008 Type: Service Changed (0x2a05)
          Data: 0200
            Indication (0x02)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #63 [hci0] 25.194371
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 21 msec (21-49 msec ~35 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 5                                      #64 [hci0] 25.344357
      ATT: Write Response (0x13) len 0
< ACL Data TX: Handle 7 flags 0x00 dlen 7                                      #65 [hci0] 25.345641
      ATT: Read Request (0x0a) len 2
        Handle: 0x0003 Type: Device Name (0x2a00)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #66 [hci0] 25.394379
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 48 msec (21-49 msec ~42 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 12                                     #67 [hci0] 25.544456
      ATT: Read Response (0x0b) len 7
< ACL Data TX: Handle 7 flags 0x00 dlen 7                                      #68 [hci0] 25.544907
      ATT: Read Request (0x0a) len 2
        Handle: 0x0005 Type: Appearance (0x2a01)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #69 [hci0] 25.594359
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (21-49 msec ~45 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 7                                      #70 [hci0] 25.744389
      ATT: Read Response (0x0b) len 2
@ MGMT Command: Disconnect (0x0014) plen 7                                {0x0001} [hci0] 32.853461
        LE Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
< HCI Command: Disconnect (0x01|0x0006) plen 3                                 #71 [hci0] 32.853529
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Reason: Remote User Terminated Connection (0x13)
> HCI Event: Command Status (0x0f) plen 4                                      #72 [hci0] 32.856314
      Disconnect (0x01|0x0006) ncmd 5
        Status: Success (0x00)
> HCI Event: Disconnect Complete (0x05) plen 4                                 #73 [hci0] 32.894392
        Status: Success (0x00)
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Reason: Remote User Terminated Connection (0x13)
@ MGMT Event: Command Complete (0x0001) plen 10                           {0x0001} [hci0] 32.894446
      Disconnect (0x0014) plen 7
        Status: Success (0x00)
        LE Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
gs 0x00 dlen 9                                      #62 [hci0] 25.172611
      ATT: Write Request (0x12) len 4
        Handle: 0x0009 Type: Client Characteristic Configuration (0x2902)
        Value Handle: 0x0008 Type: Service Changed (0x2a05)
          Data: 0200
            Indication (0x02)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #63 [hci0] 25.194371
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 21 msec (21-49 msec ~35 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 5                                      #64 [hci0] 25.344357
      ATT: Write Response (0x13) len 0
< ACL Data TX: Handle 7 flags 0x00 dlen 7                                      #65 [hci0] 25.345641
      ATT: Read Request (0x0a) len 2
        Handle: 0x0003 Type: Device Name (0x2a00)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #66 [hci0] 25.394379
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 48 msec (21-49 msec ~42 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 12                                     #67 [hci0] 25.544456
      ATT: Read Response (0x0b) len 7
< ACL Data TX: Handle 7 flags 0x00 dlen 7                                      #68 [hci0] 25.544907
      ATT: Read Request (0x0a) len 2
        Handle: 0x0005 Type: Appearance (0x2a01)
> HCI Event: Number of Completed Packets (0x13) plen 5                         #69 [hci0] 25.594359
        Num handles: 1
        Handle: 7 Address: F6:0C:C0:F5:66:52 (OUI F6-0C-C0)
        Count: 1
        Latency: 49 msec (21-49 msec ~45 msec)
> ACL Data RX: Handle 7 flags 0x02 dlen 7                                      #70 [hci0] 25.744389
      ATT: Read Response (0x0b) len 2
```

**Comment by dlech** [comment]
This looks like an issue with https://github.com/Bluetooth-Devices/dbus-fast, not Bleak.
