### ISSUE TITLE
[Andorid]bleak.exc.BleakError: ('onConnectionStateChange', 'Insufficient Authorization', 0)

### ISSUE THREAD

**Issue by tsiens** [hbldh/bleak#1696]
* bleak version: 0.22.3
* Python version: 3.11.0
* Operating System: android
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

I have packaged a Flask single-threaded app using p4a WebView. When I use Bleak and intentionally turn off the Bluetooth Low Energy (BLE) power, an error occurs and the entire app becomes unresponsive and crashes. This issue does not occur in Windows.

### Logs
```
12-10 22:38:34.273 20315 20406 I python  : Exception in callback AsyncJavaCallbacks._result_state_unthreadsafe('Insufficient Authorization', 'onConnectionStateChange', (0,))
12-10 22:38:34.273 20315 20406 I python  : handle: <Handle AsyncJavaCallbacks._result_state_unthreadsafe('Insufficient Authorization', 'onConnectionStateChange', (0,))>
12-10 22:38:34.273 20315 20406 I python  : Traceback (most recent call last):
12-10 22:38:34.273 20315 20406 I python  :   File "/home/user/.local/share/python-for-android/build/other_builds/python3/arm64-v8a__ndk_target_24/python3/Lib/asyncio/events.py", line 80, in _run
12-10 22:38:34.273 20315 20406 I python  :   File "/home/user/.local/share/python-for-android/build/python-installs/tda/arm64-v8a/bleak/backends/p4android/utils.py", line 94, in _result_state_unthreadsafe    
12-10 22:38:34.273 20315 20406 I python  : bleak.exc.BleakError: ('onConnectionStateChange', 'Insufficient Authorization', 0)
```

**Comment by tsiens** [comment]
I tried to read it after shutting down, but it froze without setting a disconnect callback
