### ISSUE TITLE
AttributeError: 'BleakDataWriter' object has no attribute 'DetachBuffer'

### ISSUE THREAD

**Issue by trflorian** [hbldh/bleak#402]
* bleak version: 0.10.0
* Python version: 3.7.0
* Operating System: Windows 10
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

I am trying to write to a descriptor.

### What I Did

1) Create BeakClient
2) Await connection
3) Write to any available descriptor

```
Traceback (most recent call last):
  File "spherov2_test.py", line 65, in <module>
    loop.run_until_complete(run(address, True))
  File "C:\Users\flori\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "spherov2_test.py", line 47, in run
    await client.write_gatt_descriptor(DFU_descriptor.handle,struct.pack('<bb', 0x01, 0x00))
  File "C:\Users\flori\AppData\Local\Programs\Python\Python37\lib\site-packages\bleak\backends\dotnet\client.py", line 714, in write_gatt_descriptor
    descriptor.obj.WriteValueAsync(writer.DetachBuffer())
AttributeError: 'BleakDataWriter' object has no attribute 'DetachBuffer'
```

**Comment by trflorian** [comment]
I think this problem lies in the dotnet client, there is a typo when calling the detach buffer method. One time it is DetachBuffer() and another time its detach_buffer(), where the latter is the correct one.
