### ISSUE TITLE
Trouble connecting to iPhone from Linux

### ISSUE THREAD

**Issue by cspensky** [hbldh/bleak#411]
* bleak version: dbus-next-2 (branch)
* Python version: Python 3.8.0
* Operating System: Ubuntu 18.04.5 LTS
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.54

### Description

Trying to initiate a simple connection with my phones.

### What I Did

I ran a simple connect script, and cannot seem to get Linux to connect to my iPhone.  Has anyone else had issues?

My test script:
```python
import asyncio
import platform

from bleak import BleakClient, BleakScanner


async def print_services(mac_addr: str):
    device = await BleakScanner.find_device_by_address(mac_addr)
    async with BleakClient(device) as client:
        svcs = await client.get_services()
        print("Services:", svcs)


# iPhone XR
mac_addr_iphone = (
    "f4:af:e7:a9:7b:7b"
    if platform.system() != "Darwin"
    else "5B18BB9D-EE12-40F2-AC66-C39BA6804410"
)

# Pixel 5
mac_addr_android = (
    "4b:31:c7:a8:69:8d"
    if platform.system() != "Darwin"
    else "906D3D50-776F-47E2-9B00-A566F75E8CCF"
)

print("Android")
loop = asyncio.get_event_loop()
loop.run_until_complete(print_services(mac_addr_android))

print("iPhone")
loop = asyncio.get_event_loop()
loop.run_until_complete(print_services(mac_addr_iphone))
```

OSX:
```bash
$ python linux_iphone.py
Android
Services: <bleak.backends.service.BleakGATTServiceCollection object at 0x10d3bf130>
iPhone
Services: <bleak.backends.service.BleakGATTServiceCollection object at 0x10d3bfb80>
```

Linux:
```bash
$ python linux_iphone.py
Android
Services: <bleak.backends.service.BleakGATTServiceCollection object at 0x7f6ae5eef340>
iPhone
Traceback (most recent call last):
  File "linux_iphone.py", line 38, in <module>
    loop.run_until_complete(print_services(mac_addr_iphone))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "linux_iphone.py", line 13, in print_services
    async with BleakClient(device) as client:
  File "bleak/bleak/backends/client.py", line 59, in __aenter__
    await self.connect()
  File "bleak/bleak/backends/bluezdbus/client.py", line 290, in connect
    assert_reply(reply)
  File "bleak/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name)
bleak.exc.BleakDBusError: org.bluez.Error.Failed
```

**Comment by dlech** [comment]
Can you run with debug logging enabled and post the logs for the failure?

**Comment by cspensky** [comment]
Here is the relevant portion:
```bash
iPhone
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:bleak.backends.bluezdbus.scanner:cached devices: {'/org/bluez/hci0/dev_54_B0_CE_EF_38_97': {'Address': '54:B0:CE:EF:38:97', 'AddressType': 'public', 'Name': 'SENSE  ', 'Alias': 'SENSE  ', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x06\xad\x01\xc6\x93\x89\n\xc4\xb1\x06\x00\x01\x00\x01\x02'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_F1_A9_4E_90_BC_65': {'Address': 'F1:A9:4E:90:BC:65', 'AddressType': 'random', 'Alias': 'F1-A9-4E-90-BC-65', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000feed-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServiceData': {'0000feed-0000-1000-8000-00805f9b34fb': b'\x02\x00\xab\x12\x1b\xe4>i\x08R'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_E7_1A_68_63_94_EA': {'Address': 'E7:1A:68:63:94:EA', 'AddressType': 'random', 'Name': 'Tile', 'Alias': 'Tile', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000feed-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServiceData': {'0000feed-0000-1000-8000-00805f9b34fb': b'\x02\x00\x18\xc9SA\x137\xc0\xc1'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_77_CB_C7_5A_13_7D': {'Address': '77:CB:C7:5A:13:7D', 'AddressType': 'random', 'Alias': '77-CB-C7-5A-13-7D', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['50400001-b5a3-f393-e0a9-e50e24dcca9e'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, '/org/bluez/hci0/dev_6B_D1_C2_9D_65_CB': {'Address': '6B:D1:C2:9D:65:CB', 'AddressType': 'random', 'Alias': '6B-D1-C2-9D-65-CB', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x10\x05\x01\x98\xd1\xf4\x05'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_CC_98_8B_B7_2A_FA': {'Address': 'CC:98:8B:B7:2A:FA', 'AddressType': 'public', 'Name': 'LE_WH-1000XM3', 'Alias': 'LE_WH-1000XM3', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000fe03-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServiceData': {'0000fe26-0000-1000-8000-00805f9b34fb': b'\n\xc9\\'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_4E_C8_9E_32_B5_EB': {'Address': '4E:C8:9E:32:B5:EB', 'AddressType': 'random', 'Alias': '4E-C8-9E-32-B5-EB', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000fe50-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServiceData': {'0000fe50-0000-1000-8000-00805f9b34fb': b'\xd6\x00'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_3C_C9_BF_CC_1A_65': {'Address': '3C:C9:BF:CC:1A:65', 'AddressType': 'random', 'Alias': '3C-C9-BF-CC-1A-65', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000fd6f-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServiceData': {'0000fd6f-0000-1000-8000-00805f9b34fb': b'\xf7\xf8\xe9\x87k\xbe\xebZ-o%\xa2\x7f\xc5tP\xa9#\xdf\x16'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_38_18_4C_1A_22_73': {'Address': '38:18:4C:1A:22:73', 'AddressType': 'public', 'Name': 'LE_WH-1000XM3', 'Alias': 'LE_WH-1000XM3', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000fe03-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, '/org/bluez/hci0/dev_79_2D_35_89_C2_05': {'Address': '79:2D:35:89:C2:05', 'AddressType': 'random', 'Alias': '79-2D-35-89-C2-05', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_44_EA_28_D3_4F_3A': {'Address': '44:EA:28:D3:4F:3A', 'AddressType': 'random', 'Alias': '44-EA-28-D3-4F-3A', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['50400001-b5a3-f393-e0a9-e50e24dcca9e'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, '/org/bluez/hci0/dev_76_88_5C_09_C4_CF': {'Address': '76:88:5C:09:C4:CF', 'AddressType': 'random', 'Alias': '76-88-5C-09-C4-CF', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_F8_FF_C2_20_EC_25': {'Address': 'F8:FF:C2:20:EC:25', 'AddressType': 'public', 'Alias': 'F8-FF-C2-20-EC-25', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x10\x05N\x1c/6e'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_20_99_0D_1B_5C_BB': {'Address': '20:99:0D:1B:5C:BB', 'AddressType': 'random', 'Alias': '20-99-0D-1B-5C-BB', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000fd6f-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ServiceData': {'0000fd6f-0000-1000-8000-00805f9b34fb': b"\x99%A~~X\x85'}Vzg\xa4\x06\xdfp\x9b\xa6\xed\xf7"}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_5A_E3_87_F0_C8_36': {'Address': '5A:E3:87:F0:C8:36', 'AddressType': 'random', 'Alias': '5A-E3-87-F0-C8-36', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['50400001-b5a3-f393-e0a9-e50e24dcca9e'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, '/org/bluez/hci0/dev_4C_D1_80_EA_88_E6': {'Address': '4C:D1:80:EA:88:E6', 'AddressType': 'random', 'Alias': '4C-D1-80-EA-88-E6', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x10\x05\x1f\x18A\xfdB'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_F3_33_22_C2_CB_E0': {'Address': 'F3:33:22:C2:CB:E0', 'AddressType': 'random', 'Name': 'B4E5532B654033AEE9', 'Alias': 'B4E5532B654033AEE9', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000fe07-0000-1000-8000-00805f9b34fb'], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {1447: b'\x04\x10\x01\x00\x00\x00\x00\x00\x00\x00\x16\x00\xca'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_7A_64_23_04_01_66': {'Address': '7A:64:23:04:01:66', 'AddressType': 'random', 'Alias': '7A-64-23-04-01-66', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x0c\x0e\x00\xa4/\xdeLz~\xda\nT\x15l\xf3\x96'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_69_55_E8_73_43_C4': {'Address': '69:55:E8:73:43:C4', 'AddressType': 'random', 'Name': 'sda', 'Alias': 'sda', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['50400001-b5a3-f393-e0a9-e50e24dcca9e'], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_05_96_DE_59_45_14': {'Address': '05:96:DE:59:45:14', 'AddressType': 'random', 'Alias': '05-96-DE-59-45-14', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\n\x01\x00'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_75_05_EB_0B_6B_A2': {'Address': '75:05:EB:0B:6B:A2', 'AddressType': 'random', 'Alias': '75-05-EB-0B-6B-A2', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_53_9F_D9_06_62_B8': {'Address': '53:9F:D9:06:62:B8', 'AddressType': 'random', 'Alias': '53-9F-D9-06-62-B8', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x10\x05E\x1cM\xd3\xd1'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_74_9F_9C_70_18_29': {'Address': '74:9F:9C:70:18:29', 'AddressType': 'random', 'Name': 'Pixel 5', 'Alias': 'Pixel 5', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': True, 'UUIDs': ['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '50400001-b5a3-f393-e0a9-e50e24dcca9e'], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': True}, '/org/bluez/hci0/dev_5C_09_47_B2_95_04': {'Address': '5C:09:47:B2:95:04', 'AddressType': 'public', 'Name': 'Bernie’s Phone', 'Alias': 'Bernie’s Phone', 'Appearance': 64, 'Icon': 'phone', 'Paired': True, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['00000000-deca-fade-deca-deafdecacafe', '00001000-0000-1000-8000-00805f9b34fb', '0000110a-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '00001116-0000-1000-8000-00805f9b34fb', '0000111f-0000-1000-8000-00805f9b34fb', '0000112f-0000-1000-8000-00805f9b34fb', '00001132-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '02030302-1d19-415f-86f2-22a2106a0a77'], 'Modalias': 'bluetooth:v004Cp710Dd0E30', 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_B8_53_AC_DA_8D_07': {'Address': 'B8:53:AC:DA:8D:07', 'AddressType': 'public', 'Name': 'sda', 'Alias': 'sda', 'Appearance': 64, 'Icon': 'phone', 'Paired': True, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '00001805-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb', '0000180f-0000-1000-8000-00805f9b34fb', '7905f431-b5ce-4e99-a40f-4b1e122d00d0', '89d3502b-0f36-433a-8ef4-c502ad55f8dc', '9fa480e0-4967-4542-9390-d343dc5d04ae', 'd0611e78-bbb4-4591-a5f8-487910ae4366'], 'Adapter': '/org/bluez/hci0', 'ManufacturerData': {76: b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04'}, 'ServicesResolved': False}, '/org/bluez/hci0/dev_F4_AF_E7_A9_7B_7B': {'Address': 'F4:AF:E7:A9:7B:7B', 'AddressType': 'public', 'Name': 'sda', 'Alias': 'sda', 'Class': 7995916, 'Icon': 'phone', 'Paired': True, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['00000000-deca-fade-deca-deafdecacafe', '00001000-0000-1000-8000-00805f9b34fb', '0000110a-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '00001116-0000-1000-8000-00805f9b34fb', '0000111f-0000-1000-8000-00805f9b34fb', '0000112f-0000-1000-8000-00805f9b34fb', '00001132-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '00001800-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '00001805-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb', '0000180f-0000-1000-8000-00805f9b34fb', '02030302-1d19-415f-86f2-22a2106a0a77', '50400001-b5a3-f393-e0a9-e50e24dcca9e', '7905f431-b5ce-4e99-a40f-4b1e122d00d0', '89d3502b-0f36-433a-8ef4-c502ad55f8dc', '9fa480e0-4967-4542-9390-d343dc5d04ae', 'd0611e78-bbb4-4591-a5f8-487910ae4366'], 'Modalias': 'bluetooth:v004Cp7238d0E00', 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}}
DEBUG:bleak.backends.bluezdbus.scanner:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0): ['org.bluez.Adapter1', {'Discovering': <dbus_next.signature.Variant ('b', True)>}, []]
DEBUG:bleak.backends.bluezdbus.scanner:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_F4_AF_E7_A9_7B_7B): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -59)>, 'TxPower': <dbus_next.signature.Variant ('n', 12)>}, []]
DEBUG:bleak.backends.bluezdbus.scanner:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_F3_33_22_C2_CB_E0): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -71)>, 'TxPower': <dbus_next.signature.Variant ('n', 0)>}, []]
DEBUG:bleak.backends.bluezdbus.scanner:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0): ['org.bluez.Adapter1', {'Discovering': <dbus_next.signature.Variant ('b', False)>}, []]
DEBUG:bleak.backends.bluezdbus.scanner:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_F3_33_22_C2_CB_E0): ['org.bluez.Device1', {}, ['TxPower', 'RSSI']]
DEBUG:bleak.backends.bluezdbus.scanner:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_F4_AF_E7_A9_7B_7B): ['org.bluez.Device1', {}, ['TxPower', 'RSSI']]
DEBUG:bleak.backends.bluezdbus.client:Connecting to device @ F4:AF:E7:A9:7B:7B with hci0
DEBUG:bleak.backends.bluezdbus.client:received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_F4_AF_E7_A9_7B_7B): ['org.bluez.Device1', {'Connected': <dbus_next.signature.Variant ('b', True)>, 'Name': <dbus_next.signature.Variant ('s', Chad’s iPhone)>, 'Alias': <dbus_next.signature.Variant ('s', Chad’s iPhone)>}, []]
DEBUG:bleak.backends.bluezdbus.client:_remove_signal_handlers(/org/bluez/hci0/dev_F4_AF_E7_A9_7B_7B)
DEBUG:bleak.backends.bluezdbus.client:_disconnect_message_bus(/org/bluez/hci0/dev_F4_AF_E7_A9_7B_7B)
Traceback (most recent call last):
  File "linux_iphone.py", line 39, in <module>
    loop.run_until_complete(print_services(mac_addr_iphone))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "linux_iphone.py", line 14, in print_services
    async with BleakClient(device) as client:
  File "/home/cspensky/allthenticate/core/python-libary/repositories/bleak/bleak/backends/client.py", line 59, in __aenter__
    await self.connect()
  File "/home/cspensky/allthenticate/core/python-libary/repositories/bleak/bleak/backends/bluezdbus/client.py", line 290, in connect
    assert_reply(reply)
  File "/home/cspensky/allthenticate/core/python-libary/repositories/bleak/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name)
bleak.exc.BleakDBusError: org.bluez.Error.Failed
```

**Comment by dlech** [comment]
Interesting, we get the property change indicating that it did connect but the connect method fails. Looking through the [BlueZ source code](https://github.com/bluez/bluez/blob/c96d5ec7aafc8fd988f6f19b896115853b951d91/src/device.c#L5430) it looks like this can mean that another connection is in progress or there is an issue with bonding (I don't know anything about how bonding works).

**Comment by dlech** [comment]
Although the latter may actually print an error message for `bluetoothd`. Try checking `sudo journalctl -R` or `sudo systemctl status bluetooth.service`.

**Comment by cspensky** [comment]
Interesting.  BlueZ is definitely unhappy.

```bash
bluetoothd[17724]: connect error: Invalid exchange (52)
```

**Comment by dlech** [comment]
I guess the next step is `wireshark` to see what is really going on.

**Comment by dlech** [comment]
Also that "connect error" seems to be removed in BlueZ master, so maybe something that is fixed upstream already?

**Comment by dlech** [comment]
https://stackoverflow.com/questions/43106595/what-does-python-socket-error-no-52-invalid-exchange-refer-to

**Comment by cspensky** [comment]
I see... It seems like it has to do with pairing and requiring a PIN.

`btmon` output:
```bash
> HCI Event: Remote Name Req Complete (0x07) plen 255                                                                  #114 [hci0] 6.641460
        Status: Success (0x00)
        Address: F4:AF:E7:A9:7B:7B (OUI F4-AF-E7)
        Name: Chad’s iPhone
@ MGMT Event: Device Connected (0x000b) plen 30                                                                    {0x0003} [hci0] 6.641526
        BR/EDR Address: F4:AF:E7:A9:7B:7B (OUI F4-AF-E7)
        Flags: 0x00000000
        Data length: 17
        Name (complete): Chad’s iPhone
@ MGMT Event: Device Connected (0x000b) plen 30                                                                    {0x0001} [hci0] 6.641526
        BR/EDR Address: F4:AF:E7:A9:7B:7B (OUI F4-AF-E7)
        Flags: 0x00000000
        Data length: 17
        Name (complete): Chad’s iPhone
< HCI Command: Authentication Requested (0x01|0x0011) plen 2                                                           #115 [hci0] 6.641566
        Handle: 12
> HCI Event: Command Status (0x0f) plen 4                                                                              #116 [hci0] 6.643424
      Authentication Requested (0x01|0x0011) ncmd 1
        Status: Success (0x00)
> HCI Event: Link Key Request (0x17) plen 6                                                                            #117 [hci0] 6.644418
        Address: F4:AF:E7:A9:7B:7B (OUI F4-AF-E7)
< HCI Command: Link Key Request Reply (0x01|0x000b) plen 22                                                            #118 [hci0] 6.644457
        Address: F4:AF:E7:A9:7B:7B (OUI F4-AF-E7)
        Link key: 2228da60bf8e0964bb24a71d98f7afab
> HCI Event: Command Complete (0x0e) plen 10                                                                           #119 [hci0] 6.646440
      Link Key Request Reply (0x01|0x000b) ncmd 1
        Status: Success (0x00)
        Address: F4:AF:E7:A9:7B:7B (OUI F4-AF-E7)
> HCI Event: Auth Complete (0x06) plen 3                                                                               #120 [hci0] 6.651415
        Status: PIN or Key Missing (0x06)
        Handle: 12
@ MGMT Event: Authentication Failed (0x0011) plen 8                                                                {0x0003} [hci0] 6.651451
        BR/EDR Address: F4:AF:E7:A9:7B:7B (OUI F4-AF-E7)
        Status: Authentication Failed (0x05)
@ MGMT Event: Authentication Failed (0x0011) plen 8                                                                {0x0001} [hci0] 6.651451
        BR/EDR Address: F4:AF:E7:A9:7B:7B (OUI F4-AF-E7)
        Status: Authentication Failed (0x05)
= bluetoothd: connect error: Invalid exchange (52)                                                                                 6.653238
< HCI Command: Disconnect (0x01|0x0006) plen 3                                                                         #121 [hci0] 6.675749
        Handle: 12
        Reason: Remote User Terminated Connection (0x13)
```

**Comment by dlech** [comment]
Did you try removing the device using `bluetoothctl`? 

The BlueZ connect method is goofy and tries to guess if you want a LE or BR/EDR (classic) connection. I'm not sure why there isn't a dedicated method for connecting LE only.

**Comment by cspensky** [comment]
It's definitely something with pairing. If I set `pairable off` it will not connect and ask me to connect with a PIN.  `agent off` makes it even more exciting by popping the message up only briefly.  I'll report back after I dig in a bit.  Thanks for the sounding board!

**Comment by cspensky** [comment]
After much digging, it appears to be BlueZ trying to read the battery status of my iPhone when I connect.  

I attached [PacketLogger to my iPhone](https://www.bluetooth.com/blog/a-new-way-to-debug-iosbluetooth-applications/) and it looks like Apple requires authentication to read that characteristic.
![image](https://user-images.githubusercontent.com/2789577/103833602-3dc97100-5036-11eb-8501-ed805bc99312.png)

Odd behavior indeed and the fact that it is doing it by default, without a flag is pretty annoying.  Is this a Bleak thing?  Any insights into how to turn this off would be great.  Otherwise, I plan to continue to dig, and potentially submit a PR to the BlueZ folks.

**Comment by dlech** [comment]
Try the suggestion at https://github.com/hbldh/bleak/issues/393#issue-765523895 to disable the battery plugin in BlueZ.

**Comment by cspensky** [comment]
That worked! Thanks a million. 🙏
