### ISSUE TITLE
ble pair fails even windows UI prompt succeed

### ISSUE THREAD

**Issue by barron9** [hbldh/bleak#417]
```python
import asyncio
from bleak import BleakScanner, BleakClient

async def run():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d.address + d.name)
        async with BleakClient(d) as client:
            res = await client.pair(protection_level=None)
            print(res)

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```
device is paired but the res is : 
```
bleak.exc.BleakError: Could not pair with device: 15: OperationAlreadyInProgress
```

**Comment by hbldh** [comment]
Note that it is not guaranteed that you will successfully be able to pair with all devices you discover. It might work to pair using Bleak, given that the device does not need any additional encryption and no confirmations.

There is a bug in the current version of Bleak regarding pairing, but if you install the version found in the `feature/pairing-improvement-dotnet`. Try installing that and then run this code and report the results here:

```python
import asyncio
from bleak import BleakScanner, BleakClient

async def run():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d.address + d.name)
        async with BleakClient(d) as client:
            print(f"CanPair: {client._requester.DeviceInformation.Pairing.CanPair}")
            print(f"IsPaired: {client._requester.DeviceInformation.Pairing.IsPaired}")
            res = await client.pair(protection_level=None)
            print(res)

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

**Comment by NikitaKozlovtcev** [comment]
I also cannot connect to the BLE device. The code above gives this error. 
```python
Traceback (most recent call last):
  File "C:/REP/Development/Tools/BLE/main.py", line 41, in <module>
    loop.run_until_complete(run())
  File "C:\Users\Nikita_Kozlovtsev\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/REP/Development/Tools/BLE/main.py", line 22, in run
    async with BleakClient(d) as client:
  File "C:\Users\Nikita_Kozlovtsev\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bleak\backends\client.py", line 59, in __aenter__
    await self.connect()
  File "C:\Users\Nikita_Kozlovtsev\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bleak\backends\dotnet\client.py", line 231, in connect
    await asyncio.wait_for(event.wait(), timeout=10)
  File "C:\Users\Nikita_Kozlovtsev\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

**Comment by hbldh** [comment]
Try a longer timeout: `async with BleakClient(d, timeout=30) as client:`

**Comment by NikitaKozlovtcev** [comment]
> Try a longer timeout: `async with BleakClient(d, timeout=30) as client:`

it really makes mistakes less. But requests for 30 seconds are very long. I wrote more about my case here
https://github.com/hbldh/bleak/issues/452
