### ISSUE TITLE
dbus-next backend: Connection was not successful!

### ISSUE THREAD

**Issue by lhammond** [hbldh/bleak#440]
* bleak version: dbus-next-2 branch bleak-0.11.0a1-py3.6.egg
* Python version: 3.6.9
* Operating System: Ubuntu 18.04
* BlueZ version 5.48

### Description

All examples fail with 

`bleak/backends/bluezdbus/client.py", line 321, in connect
    f"Connection was not successful! ({self._device_path})"
bleak.exc.BleakError: Connection was not successful! (/org/bluez/hci0/dev_68_27_19_21_E1_FF)`

```
Traceback (most recent call last):
  File "examples/service_explorer.py", line 67, in <module>
    loop.run_until_complete(run(address, True))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "examples/service_explorer.py", line 28, in run
    async with BleakClient(address) as client:
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/clh/projects/bluedog-edge/pygatt-venv/lib/python3.6/site-packages/bleak-0.11.0a1-py3.6.egg/bleak/backends/client.py", line 59, in __aenter__
    await self.connect()
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/clh/projects/bluedog-edge/pygatt-venv/lib/python3.6/site-packages/bleak-0.11.0a1-py3.6.egg/bleak/backends/bluezdbus/client.py", line 321, in connect
    f"Connection was not successful! ({self._device_path})"
bleak.exc.BleakError: Connection was not successful! (/org/bluez/hci0/dev_68_27_19_21_E1_FF)
```

I do see a connect/disconnect twice in bluetoothctl output

![image](https://user-images.githubusercontent.com/229602/107054131-bb031580-679d-11eb-8127-d0bb14c9884d.png)

**Comment by dlech** [comment]
What sort of device are you connecting to? 

We had some report a similar issue with an iPhone and it turned out the be that BlueZ was trying to also connect to the battery service in the background but it failed because it required a secure connection or something like that. The workaround was to disable the battery plugin in BlueZ.
