### ISSUE TITLE
Device returned by detection callback is not properly initialized on corebluetooth

### ISSUE THREAD

**Issue by nonameforgood** [hbldh/bleak#448]
* bleak version:0.10.0
* Python version:3.7.2
* Operating System:MacOS Catalina 10.15.2
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

The device returned by the detection callback is missing "delegate" which is needed by the ctor of BleakClientCoreBluetooth

### What I Did

I work around the issue by not using the callback and repeatedly calling get_discovered_devices instead.

Sample (modified from bleak/examples/detection_callback.py):
```python
import asyncio
from bleak import BleakScanner
from bleak import BleakClient
from bleak.backends.device import BLEDevice
from bleak.backends.scanner import AdvertisementData
import logging

logging.basicConfig()

dev = None

def simple_callback(device: BLEDevice, advertisement_data: AdvertisementData):
    global dev
    dev = device
    print(device.address, "RSSI:", device.rssi, advertisement_data)


async def run():
    scanner = BleakScanner()
    scanner.register_detection_callback(simple_callback)

    while True:
        await scanner.start()
        await asyncio.sleep(5.0)
        await scanner.stop()

        global dev
        if dev is not None:
            async with BleakClient(dev) as client:
                print("Connected") 


loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

Command line:
```
python3 detect_sample.py
```
Output:
```
Traceback (most recent call last):
  File "detect_sample.py", line 35, in <module>
    loop.run_until_complete(run())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "detect_sample.py", line 30, in run
    async with BleakClient(dev) as client:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bleak/backends/corebluetooth/client.py", line 51, in __init__
    self._central_manager_delegate = address_or_ble_device.metadata["delegate"]
KeyError: 'delegate'
```

**Comment by nonameforgood** [comment]
Awesome thanks
