### ISSUE TITLE
WIN10 NotImplementedError error during connect "connect_by_bledevice.py" 

### ISSUE THREAD

**Issue by pawelm87** [hbldh/bleak#589]
* bleak version: 0.12.0
* Python version: 3.7.4
* Operating System: WIN10
* BlueZ version (`bluetoothctl -v`) in case of Linux: None

### Description

My script using the bleakk==0.11.0 library connects to devices correctly, when I upgraded the library to version 0.12.0 when connecting to a device I get a NotImplementedError.

I tried running the example "connect_by_bledevice.py" and I get the same error.

### What I Did

```python
import asyncio

from bleak import BleakClient, BleakScanner
from bleak.exc import BleakError


async def print_services(ble_address: str):
    print("1--------------------------")
    device = await BleakScanner.find_device_by_address(ble_address, timeout=20.0)
    print("2--------------------------", device)
    if not device:
        print("3--------------------------")
        raise BleakError(f"A device with address {ble_address} could not be found.")
    async with BleakClient(device) as client:
        print("4--------------------------")
        svcs = await client.get_services()
        print("Services:")
        for service in svcs:
            print(service)


loop = asyncio.get_event_loop()
loop.run_until_complete(print_services("F7:D6:B8:83:F3:08"))
```

Error:

```
PS C:\Users\p\Desktop\PM\workspace\python\cli-tool> & C:\Users\p\Desktop\PM\workspace\python\VENV\Scripts\python.exe .\bleak_scan.py
1--------------------------
2-------------------------- F7:D6:B8:83:F3:08: DEV01
Traceback (most recent call last):
  File ".\bleak_scan.py", line 29, in <module>
    loop.run_until_complete(print_services("F7:D6:B8:83:F3:08"))
  File "C:\Users\p\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File ".\bleak_scan.py", line 20, in print_services
    async with BleakClient(device, timeout=20.0) as client:
  File "C:\Users\pa\Desktop\PM\workspace\python\VENV\lib\site-packages\bleak\backends\client.py", line 61, in __aenter__
    await self.connect()
  File "C:\Users\p\Desktop\PM\workspace\python\VENV\lib\site-packages\bleak\backends\winrt\client.py", line 227, in connect
    await self.get_services(use_cached=use_cached)
  File "C:\Users\p\Desktop\PM\workspace\python\VENV\lib\site-packages\bleak\backends\winrt\client.py", line 495, in get_services
    str(characteristic.uuid),
NotImplementedError
PS C:\Users\p\Desktop\PM\workspace\python\cli-tool> & C:\Users\p\Desktop\PM\workspace\python\VENV\Scripts\python.exe --version
Python 3.7.4
PS C:\Users\p\Desktop\PM\workspace\python\cli-tool> & C:\Users\p\Desktop\PM\workspace\python\VENV\Scripts\pip show bleak
Name: bleak
Version: 0.12.0
Summary: Bluetooth Low Energy platform Agnostic Klient
Home-page: https://github.com/hbldh/bleak
Author: Henrik Blidh
Author-email: henrik.blidh@nedomkull.com
License: MIT
Location: c:\users\p\desktop\pm\workspace\python\venv\lib\site-packages
Requires: pythonnet
Required-by:

PS C:\Users\p\Desktop\PM\workspace\python\cli-tool> & C:\Users\p\Desktop\PM\workspace\python\VENV\Scripts\pip.exe install bleak==0.11.0
Collecting bleak==0.11.0
  Using cached https://files.pythonhosted.org/packages/80/ee/75b41754259f9aa59b2561544fc029da9744bfeb350dde22d8855f417a92/bleak-0.11.0-py2.py3-none-any.whl
Requirement already satisfied: pythonnet; platform_system == "Windows" in c:\users\p\desktop\pm\pm\python\venv\lib\site-packages (from bleak==0.11.0) (2.5.1)
Requirement already satisfied: pycparser in c:\users\p\desktop\pm\workspace\python\venv\lib\site-packages (from pythonnet; platform_system == "Windows"->bleak==0.11.0) (2.20)
Installing collected packages: bleak
  Found existing installation: bleak 0.12.0
    Uninstalling bleak-0.12.0:
      Successfully uninstalled bleak-0.12.0
Successfully installed bleak-0.11.0
You are using pip version 19.0.3, however version 21.1.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\p\Desktop\PM\workspace\python\-cli-tool> & C:\Users\p\Desktop\PM\workspace\python\VENV\Scripts\python.exe .\bleak_scan.py
1--------------------------
2-------------------------- F7:D6:B8:83:F3:08: LNPP-1.0.7
4--------------------------
Services:
00001800-0000-1000-8000-00805f9b34fb (Handle: 1): Generic Access Profile
00001801-0000-1000-8000-00805f9b34fb (Handle: 8): Generic Attribute Profile
51311102-030e-485f-b122-f8f381aa9020 (Handle: 11): Unknown
PS C:\Users\p\Desktop\PM\workspace\python\-cli-tool>
```

**Comment by pawelm87** [comment]
I try do it on MacOS

```
yj-osx:Documents user$ python3.7 bleak_scan.py
1--------------------------
2-------------------------- 166AAC6E-837F-408D-B77D-3A382C746EE4: DEV01
4--------------------------
Services:
51311102-030e-485f-b122-f8f381aa9020 (Handle: 11): Unknown
yj-osx:Documents user$ pip3 show bleak
Name: bleak
Version: 0.12.0
Summary: Bluetooth Low Energy platform Agnostic Klient
Home-page: https://github.com/hbldh/bleak
Author: Henrik Blidh
Author-email: henrik.blidh@nedomkull.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: pyobjc-core, pyobjc-framework-libdispatch, pyobjc-framework-CoreBluetooth
Required-by:
```

**Comment by pawelm87** [comment]
I installed a new version of the library but it did not solve the problem:

tested script:
```
"""
Connect by BLEDevice
"""

import asyncio

from bleak import BleakClient, BleakScanner
from bleak.exc import BleakError


async def print_services(ble_address: str):
    print("1--------------------------")
    device = await BleakScanner.find_device_by_address(ble_address, timeout=20.0)
    print("2--------------------------", device)
    if not device:
        print("3--------------------------")
        raise BleakError(f"A device with address {ble_address} could not be found.")
    async with BleakClient(device) as client:
        print("4--------------------------")
        svcs = await client.get_services()
        print("Services:")
        for service in svcs:
            print(service)


loop = asyncio.get_event_loop()
loop.run_until_complete(print_services("E4:D0:AE:38:71:7E"))
```

and the result:
```
PS C:\Users\p\Desktop\PM\workspace\python\cli-tool> & C:\Users\p\Desktop\PM\workspace\python\VENV-cli-tool\Scripts\python.exe .\bleak_scan.py
1--------------------------
2-------------------------- E4:D0:AE:38:71:7E: LNPC-1.0.8
Traceback (most recent call last):
  File ".\bleak_scan.py", line 27, in <module>
    loop.run_until_complete(print_services("E4:D0:AE:38:71:7E"))
  File "C:\Users\p\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File ".\bleak_scan.py", line 18, in print_services
    async with BleakClient(device) as client:
  File "C:\Users\p\Desktop\PM\workspace\python\VENV-cli-tool\lib\site-packages\bleak\backends\client.py", line 61, in __aenter__
    await self.connect()
  File "C:\Users\p\Desktop\PM\workspace\python\VENV-cli-tool\lib\site-packages\bleak\backends\winrt\client.py", line 227, in connect
    await self.get_services(use_cached=use_cached)
  File "C:\Users\p\Desktop\PM\workspace\python\VENV-cli-tool\lib\site-packages\bleak\backends\winrt\client.py", line 495, in get_services
    str(characteristic.uuid),
NotImplementedError
PS C:\Users\p\Desktop\PM\workspace\python\cli-tool> & C:\Users\p\Desktop\PM\workspace\python\VENV-cli-tool\Scripts\pip.exe show bleak
Name: bleak
Version: 0.12.1
Summary: Bluetooth Low Energy platform Agnostic Klient
Home-page: https://github.com/hbldh/bleak
Author: Henrik Blidh
Author-email: henrik.blidh@nedomkull.com
License: MIT
Location: c:\users\p\desktop\pm\workspace\python\venv-cli-tool\lib\site-packages
Requires: pythonnet
Required-by:
```
