### ISSUE TITLE
Already disconnected events and failed to remove match

### ISSUE THREAD

**Issue by elupus** [hbldh/bleak#603]
* bleak version: 0.12.1
* Python version: 3.9
* Operating System: Linux (hassos)
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

Send single command to device

```
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Connecting to device @ CC:F9:57:96:4B:7B with hci0
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -88)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -86)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'Connected': <dbus_next.signature.Variant ('b', True)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -88)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -86)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -86)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -88)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'RSSI': <dbus_next.signature.Variant ('n', -88)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): ['org.bluez.Device1', {'Connected': <dbus_next.signature.Variant ('b', False)>}, []]
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Device disconnected (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B)
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] _remove_signal_handlers(/org/bluez/hci0/dev_CC_F9_57_96_4B_7B)
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] _remove_signal_handlers(/org/bluez/hci0/dev_CC_F9_57_96_4B_7B)
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] _disconnect_message_bus(/org/bluez/hci0/dev_CC_F9_57_96_4B_7B)
2021-07-19 21:11:53 ERROR (MainThread) [bleak.backends.bluezdbus.client] Failed to remove match InterfacesAdded (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B):
2021-07-19 21:11:53 ERROR (MainThread) [bleak.backends.bluezdbus.client] Failed to remove match InterfacesRemoved (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): 'NoneType' object has no attribute 'call'
2021-07-19 21:11:53 ERROR (MainThread) [bleak.backends.bluezdbus.client] Failed to remove match PropertiesChanged (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B): 'NoneType' object has no attribute 'call'
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] _disconnect_message_bus(/org/bluez/hci0/dev_CC_F9_57_96_4B_7B)
2021-07-19 21:11:53 DEBUG (MainThread) [bleak.backends.bluezdbus.client] already disconnected (/org/bluez/hci0/dev_CC_F9_57_96_4B_7B)
2021-07-19 21:11:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140159835704768] [org.bluez.Error.Failed] Software caused connection abort
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 811, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 458, in async_handle_light_on_service
await light.async_turn_on(**filter_turn_on_params(light, params))
File "/config/custom_components/fjaraskupan/light.py", line 62, in async_turn_on
await self._device.send_command(COMMAND_LIGHT_ON_OFF)
File "/usr/local/lib/python3.9/site-packages/fjaraskupan/__init__.py", line 190, in send_command
async with self:
File "/usr/local/lib/python3.9/site-packages/fjaraskupan/__init__.py", line 130, in __aenter__
await self._client.__aenter__()
File "/usr/local/lib/python3.9/site-packages/bleak/backends/client.py", line 61, in __aenter__
await self.connect()
File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 298, in connect
assert_reply(reply)
File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Software caused connection abort
```

### What I Did

Single command against device with something similar to:

```
async with BleakClient(ble_address) as client:
  await client.write_gatt_characteristics() 
```

**Comment by elupus** [comment]
Should be noted that i think i quite a bad signal connection here. But there does seam to be some duplicate disconnection occurring here.

It could be that the connect() call will trigger cleanup, then the normal disconnect called by the aexit() will do that again.

**Comment by elupus** [comment]
dmesg gives this oddities:
```
[342229.963547] Bluetooth: hci0: advertising data len corrected 20 -> 3
[343231.341654] Bluetooth: hci0: request failed to create LE connection: status 0x0c
[343359.348233] Bluetooth: hci0: failed to disable LE scan: status 0x0c
```

**Comment by elupus** [comment]
Looks to be a result of the connect call failing, and before failing a Disconnected event has been triggered. This will do a _cleanup_all() in the event callback. Then once the exception propagate out in the connect() function, it will also do a _cleanup_all()

**Comment by elupus** [comment]
I think i may have figured out what happens here.

We get two concurrent calls to _cleanup_all(). The first one will reach the rules cleanup and consume the self._rules variables. It will then proceed to remove each rule awaiting them in turn.

The second call to _cleanup_all() will find the self._rules empty, thus it will proceed to bus disconnection. So it will end up disconnecting the bus, while the first call was removing rules.

**Comment by elupus** [comment]
A async lock around the rules cleanup instead of this emptying of rules would probably solve it.
