### ISSUE TITLE
Exception in BleakScannerBlueZDBus::start() after previous successful connection, specific to Bluez version 5.62

### ISSUE THREAD

**Issue by 0xa000** [hbldh/bleak#674]
* bleak version: 0.13.0
* Python version: 3.9.7
* Operating System: Arch Linux
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.62

### Description

I have a script that communicates with a Vernier "GoDirect" sensor using their "godirect" Python package. This package uses bleak under the hood to handle the actual BLE communication. The script uses the godirect package to find the Vernier sensor, connect to it, and read data from it via GATT.

The script worked fine until I updated to Bluez version 5.62. With this version of Bluez, every _second_ time I run the script, an exception is raised in BleakScannerBlueZDBus::start():
 
```
Traceback (most recent call last):
  File "godirect_ble_thread.py", line 66, in _acquisition_thread_main
    device = gd.get_device()
  File "/usr//lib/python3.9/site-packages/godirect/__init__.py", line 93, in get_device
    return self._ble_backend.scan_auto(threshold)
  File "/usr//lib/python3.9/site-packages/godirect/backend_bleak.py", line 49, in scan_auto
    devices = self.scan()
  File "/usr//lib/python3.9/site-packages/godirect/backend_bleak.py", line 38, in scan
    devices = loop.run_until_complete(self._async_scan())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/godirect/backend_bleak.py", line 21, in _async_scan
    bleak_devices = await discover()
  File "/usr/lib/python3.9/site-packages/bleak/backends/scanner.py", line 99, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/lib/python3.9/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/scanner.py", line 123, in start
    assert_reply(reply)
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.NoReply] Message recipient disconnected from message bus without replying
```

This only happens if the sensor is switched on. If I switch the sensor off, then I can re-run as many times as I like and scanning works fine. However, if the sensor is switched on, is found during scanning, connected to, and used, then the next time I re-run the script, it will fail with the above exception.

### What I Did

I downgraded Bluez to version 5.61 and with that version the problem described above does not occur.

With Bluez version 5.62, I see in the system journal that the bluetooth daemon exits and restarts every time the problem occurs. It seems to exit cleanly, in the sense that no error is reported in the system journal. See the excerpt below.

```
Oct 21 16:16:52 hydra bluetoothd[2517]: Disconnected from D-Bus. Exiting.
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_453
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_453
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_512
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_512
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_552
Oct 21 16:16:52 hydra bluetoothd[2517]: Endpoint unregistered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_552
Oct 21 16:16:52 hydra bluetoothd[2517]: Stopping SDP server
Oct 21 16:16:52 hydra bluetoothd[2517]: Exit
Oct 21 16:16:52 hydra systemd[1]: bluetooth.service: Deactivated successfully.
Oct 21 16:16:52 hydra audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 21 16:16:52 hydra kernel: audit: type=1131 audit(1634825812.484:232): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 21 16:16:59 hydra dbus-daemon[422]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.138' (uid=1000 pid=2533 comm="python godirect_ble_thread.py ")
Oct 21 16:16:59 hydra systemd[1]: Starting Bluetooth service...
Oct 21 16:16:59 hydra bluetoothd[2540]: Bluetooth daemon 5.62
Oct 21 16:16:59 hydra dbus-daemon[422]: [system] Successfully activated service 'org.bluez'
Oct 21 16:16:59 hydra systemd[1]: Started Bluetooth service.
Oct 21 16:16:59 hydra audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 21 16:16:59 hydra bluetoothd[2540]: Starting SDP server
Oct 21 16:16:59 hydra kernel: audit: type=1130 audit(1634825819.777:233): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=bluetooth comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 21 16:16:59 hydra bluetoothd[2540]: Bluetooth management interface 1.21 initialized
Oct 21 16:16:59 hydra bluetoothd[2540]: Failed to set privacy: Rejected (0x0b)
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_453
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_453
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_512
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_512
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSink/sbc_xq_552
Oct 21 16:17:00 hydra bluetoothd[2540]: Endpoint registered: sender=:1.61 path=/MediaEndpoint/A2DPSource/sbc_xq_552
```

For the record, the script seems to perform full bleak clean-up, as can be seen from the following log output (bleak clean-up near the end of the log):

```
| 2021-10-21 16:17:26,004 | DEBUG | godirect                | GDX >> 58  0B  F8  6F  19  FF  00  FF  FF  FF  FF
| 2021-10-21 16:17:26,004 | DEBUG | godirect                | BLE WRITE: >>>58  0B  F8  6F  19  FF  00  FF  FF  FF  FF
| 2021-10-21 16:17:26,005 | DEBUG | bleak.backends.bluezdbus.client | Write Characteristic f4bf14a6-c7d5-4b6d-8aa8-df1a7c83adcb | /org/bluez/hci0/dev_BC_33_AC_EE_85_82/service0012/char0013: b'X\x0b\xf8o\x19\xff\x00\xff\xff\xff\xff'
| 2021-10-21 16:17:26,005 | DEBUG | godirect                | lengthRemaining 0 offset 11
| 2021-10-21 16:17:26,027 | DEBUG | bleak.backends.bluezdbus.client | received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_BC_33_AC_EE_85_82/service0012/char0015): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\x98\x07\x06\xb6\x19\xf8\x00')>}, []]
| 2021-10-21 16:17:26,027 | DEBUG | godirect                | BLE NOTIFY: <<<98  07  06  B6  19  F8  00
| 2021-10-21 16:17:26,027 | DEBUG | godirect                | Receive buffer length: 7 Expected packet length: 7
| 2021-10-21 16:17:26,037 | DEBUG | godirect                | BLE READ: <<<98  07  06  B6  19  F8  00
| 2021-10-21 16:17:26,037 | DEBUG | godirect                | GDX << 98  07  06  B6  19  F8  00
| 2021-10-21 16:17:26,037 | DEBUG | godirect                | GDX >> 58  05  F7  A8  54
| 2021-10-21 16:17:26,037 | DEBUG | godirect                | BLE WRITE: >>>58  05  F7  A8  54
| 2021-10-21 16:17:26,038 | DEBUG | bleak.backends.bluezdbus.client | Write Characteristic f4bf14a6-c7d5-4b6d-8aa8-df1a7c83adcb | /org/bluez/hci0/dev_BC_33_AC_EE_85_82/service0012/char0013: b'X\x05\xf7\xa8T'
| 2021-10-21 16:17:26,038 | DEBUG | godirect                | lengthRemaining 0 offset 5
| 2021-10-21 16:17:26,056 | DEBUG | bleak.backends.bluezdbus.client | received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_BC_33_AC_EE_85_82/service0012/char0015): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\x98\x07\x07\xf1T\xf7\x00')>}, []]
| 2021-10-21 16:17:26,056 | DEBUG | godirect                | BLE NOTIFY: <<<98  07  07  F1  54  F7  00
| 2021-10-21 16:17:26,056 | DEBUG | godirect                | Receive buffer length: 7 Expected packet length: 7
| 2021-10-21 16:17:26,060 | DEBUG | godirect                | BLE READ: <<<98  07  07  F1  54  F7  00
| 2021-10-21 16:17:26,060 | DEBUG | godirect                | GDX << 98  07  07  F1  54  F7  00
| 2021-10-21 16:17:26,061 | DEBUG | bleak.backends.bluezdbus.client | received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_BC_33_AC_EE_85_82/service0012/char0015): ['org.bluez.GattCharacteristic1', {'Notifying': <dbus_next.signature.Variant ('b', False)>}, []]
| 2021-10-21 16:17:26,061 | DEBUG | bleak.backends.bluezdbus.client | Disconnecting (/org/bluez/hci0/dev_BC_33_AC_EE_85_82)
| 2021-10-21 16:17:28,377 | DEBUG | bleak.backends.bluezdbus.client | received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_BC_33_AC_EE_85_82): ['org.bluez.Device1', {'ServicesResolved': <dbus_next.signature.Variant ('b', False)>}, []]
| 2021-10-21 16:17:28,379 | DEBUG | bleak.backends.bluezdbus.client | received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_BC_33_AC_EE_85_82): ['org.bluez.Device1', {'Connected': <dbus_next.signature.Variant ('b', False)>}, []]
| 2021-10-21 16:17:28,379 | DEBUG | bleak.backends.bluezdbus.client | Device disconnected (/org/bluez/hci0/dev_BC_33_AC_EE_85_82)
| 2021-10-21 16:17:28,380 | DEBUG | bleak.backends.bluezdbus.client | _cleanup_all(/org/bluez/hci0/dev_BC_33_AC_EE_85_82)
| 2021-10-21 16:17:28,380 | INFO | __main__                | Acquisition thread stopped.
```

Note that the godirect package attempts to hide the fact the bleak is based on asyncio. It provides a completely synchronous API using `run_until_complete()` to wrap calls to asynchronous bleak functions. (Unfortunately it does not use `asyncio.run()`.) 

I guess that the fact that the bluetooth daemon exits (or crashes?) and restarts would explain the exception that the "recipient disconnected from the message bus without replying". But I do not understand how scanning after a successful connection would cause the bluetooth daemon to exit.

Of course, it may also be some problem in Bluez itself, or in the godirect package. However, since the problem manifests itself as an exception from bleak, I thought I'd report it here first.

**Comment by dlech** [comment]
I don't think there is anything to do here besides avoid this BlueZ version. BlueZ 5.64 seems to be working for many people.
