### ISSUE TITLE
InvalidStateError after callback

### ISSUE THREAD

**Issue by Xlinx64** [hbldh/bleak#675]
* bleak version: 0.13.0
* Python version: 3.9.7
* Operating System: MacOS 11.6

### Description

When the callback of a subscribed characteristic is called I get an asyncio exception.  The value which gets passed into the callback is correct.
This started happening with version 0.12.0. There is no error on 0.11.0.

```python
#!python3
import struct
import asyncio
from bleak import BleakClient, BleakScanner


UUID_HEIGHT = '99fa0021-338a-1024-8a49-009c0215f78a'


async def scan(address=None):
    scanner = BleakScanner()
    devices = await scanner.discover(device="hci0", timeout=5)
    for device in devices:
        if (device.address == address):
            return device
    return None


def callback(sender: int, data: bytearray):
    height, speed = struct.unpack("<Hh", data)
    print(height)


async def main():
    device = await scan("15D4F5E0-8BBD-426C-8426-25A9D4E5BDE3")
    client = BleakClient(device, device="hci0")
    await client.connect(timeout=10)
    initial_height, speed = struct.unpack("<Hh", await client.read_gatt_char(UUID_HEIGHT))
    await client.start_notify(UUID_HEIGHT, callback)
    print("connected")
    loop = asyncio.get_event_loop()
    wait = loop.create_future()
    await wait


if __name__ == "__main__":
    asyncio.run(main())

```

```
2212
Exception in callback PeripheralDelegate.did_update_value_for_characteristic(<CBPeripheral...e = connected>, <CBCharacteri...tifying = YES>, {length = 4, ... = 0xa408c0f3}, None)
handle: <Handle PeripheralDelegate.did_update_value_for_characteristic(<CBPeripheral...e = connected>, <CBCharacteri...tifying = YES>, {length = 4, ... = 0xa408c0f3}, None)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 333, in did_update_value_for_characteristic
    future.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state
2201
Exception in callback PeripheralDelegate.did_update_value_for_characteristic(<CBPeripheral...e = connected>, <CBCharacteri...tifying = YES>, {length = 4, ... = 0x990890f2}, None)
handle: <Handle PeripheralDelegate.did_update_value_for_characteristic(<CBPeripheral...e = connected>, <CBCharacteri...tifying = YES>, {length = 4, ... = 0x990890f2}, None)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 333, in did_update_value_for_characteristic
    future.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state
2196
Exception in callback PeripheralDelegate.did_update_value_for_characteristic(<CBPeripheral...e = connected>, <CBCharacteri...tifying = YES>, {length = 4, ... = 0x94080000}, None)
handle: <Handle PeripheralDelegate.did_update_value_for_characteristic(<CBPeripheral...e = connected>, <CBCharacteri...tifying = YES>, {length = 4, ... = 0x94080000}, None)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 333, in did_update_value_for_characteristic
    future.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by Xlinx64** [comment]
I added an example code. I also noticed that this line is the problem. When I remove it the error goes away.
```
initial_height, speed = struct.unpack("<Hh", await client.read_gatt_char(UUID_HEIGHT))
```
Did I do something wrong here?
