### ISSUE TITLE
BleakDBUSError: [org.freedesktop.DBus.Error.UnknownObject] Method "setDiscoveryFilter" doesnt exist

### ISSUE THREAD

**Issue by michael-j-potts** [hbldh/bleak#693]
* bleak version: (Installed today, pip install bleak. I imagine the most recent version?)
* Python version: Python 3.8.10
* Operating System: Ubuntu 20.04.3 LTS (64 bit) - GNOME Version 3.36.8
* BlueZ version (`bluetoothctl -v`) in case of Linux: bluetoothctl 5.53

### Description
I received this error running the test code provided below the error:

[org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
  File "/home/michael/Documents/Bluetoothtest/test.py", line 5, in main
    devices = await BleakScanner.discover()
  File "/home/michael/Documents/Bluetoothtest/test.py", line 9, in <module>
    asyncio.run(main())

```
import asyncio
from bleak import BleakScanner

async def main():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d)

asyncio.run(main())
```

### What I Did

I uninstalled and reinstalled bluez. Further, I uninstalled and reinstalled my linux operating system (to the same version), and reinstalled all the required dependencies).

I was unsure if it was just the given code, so I ran all the example code running into the same issue. 
I am new to bluetooth and unsure about which further steps to take Any advice or feedback would be greatly appreciated!

**Comment by dlech** [comment]
Can you control the Bluetooth adapter using the `bluetoothctl` command line tool?

**Comment by michael-j-potts** [comment]
Hi David,
Thanks for the quick response. Yes I am able to discover and connect
bluetooth devices with bluetoothctl.

Michael Potts

**Comment by dlech** [comment]
have you tried any [troubleshooting](https://bleak.readthedocs.io/en/latest/troubleshooting.html)? Can you share your logs?

**Comment by michael-j-potts** [comment]
I hadn't, but I have now! Here are my log outputs

First, I cleared my bluetoothctl cache (per the bottom of the document. Then I enabled bleak_logging and ran the test script listed above, resulting in this:

```
2021-12-05 17:28:00,258 bleak.backends.bluezdbus.scanner DEBUG: cached devices: {'/org/bluez/hci1/dev_8C_DE_52_AC_64_5C': {'Address': '8C:DE:52:AC:64:5C', 'AddressType': 'public', 'Name': 'Block Party Live', 'Alias': 'Block Party Live', 'Class': 2360340, 'Icon': 'audio-card', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': ['0000110b-0000-1000-8000-00805f9b34fb', '0000110e-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '00001101-0000-1000-8000-00805f9b34fb', '00000000-deca-fade-deca-deafdecacaff'], 'Adapter': '/org/bluez/hci1', 'ManufacturerData': {21321: b'SC'}, 'ServicesResolved': False}, '/org/bluez/hci1/dev_4E_5E_D6_52_37_E9': {'Address': '4E:5E:D6:52:37:E9', 'AddressType': 'random', 'Alias': '4E-5E-D6-52-37-E9', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci1', 'ManufacturerData': {76: b'\x10\x05\x0f\x1c\x0f\xf0\xc1'}, 'ServicesResolved': False}, '/org/bluez/hci1/dev_BE_FF_40_00_23_60': {'Address': 'BE:FF:40:00:23:60', 'AddressType': 'public', 'Name': 'ELK-BLEDOM ', 'Alias': 'ELK-BLEDOM ', 'Paired': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci1', 'ServicesResolved': False}}
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 5, in main
    devices = await BleakScanner.discover()
  File "/home/michael/.local/lib/python3.8/site-packages/bleak/backends/scanner.py", line 99, in discover
    async with cls(**kwargs) as scanner:
  File "/home/michael/.local/lib/python3.8/site-packages/bleak/backends/scanner.py", line 79, in __aenter__
    await self.start()
  File "/home/michael/.local/lib/python3.8/site-packages/bleak/backends/bluezdbus/scanner.py", line 145, in start
    assert_reply(reply)
  File "/home/michael/.local/lib/python3.8/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
```

**Comment by dlech** [comment]
Try adding `adapter="hci1"` to the `BleakScanner()` arguments. For some reason you don't have the default `hci0` on your system.

**Comment by michael-j-potts** [comment]
Your solution works! Thank you for your help!

I built my PC myself and am currently using a bluetooth 5.0 usb adapter. Could the issue have stemmed from one of these factors?

**Comment by dlech** [comment]
You could check the output of `dmesg` to see if a `hci0` appears or disappears if you are curious.

FYI, we have #524 that would have prevented this problem in the first place (it is currently blocked for technical reasons).

**Comment by michael-j-potts** [comment]
You are right, my computer is missing firmware for my hci0!
