### ISSUE TITLE
Cannot scan for connected devices

### ISSUE THREAD

**Issue by MagnusModig** [hbldh/bleak#729]
* bleak version: 0.13.0
* Python version: 3.9
* Operating System: Win 11
* BlueZ version (`bluetoothctl -v`) in case of Linux:

### Description

I try to scan connected devices.

### What I Did

Ran this code...
```python
import asyncio
from bleak import BleakScanner

async def main():
    devices = await BleakScanner.discover()
    for d in devices:
        print(d)

asyncio.run(main())
```

But I get this error..

```
Traceback (most recent call last):
  File "D:\scan.py", line 2, in <module>
    from bleak import BleakScanner
  File "D:\bleak.py", line 6, in <module>
    from bleak import BleakClient, BleakScanner
ImportError: cannot import name 'BleakClient' from partially initialized module 'bleak' (most likely due to a circular import) (D:\bleak.py)`

```

**Comment by dlech** [comment]
You cannot name your script `bleak.py`. This causes the circular import.

**Comment by MagnusModig** [comment]
Thanks, that helped to rename the file
