### ISSUE TITLE
Android:  FileNotFoundError: [Errno 2] No such file or directory: 'bluetoothctl'

### ISSUE THREAD

**Issue by antonelliCP** [hbldh/bleak#847]
* bleak version: 
* Python version: 3.9
* Operating System: lollipop
* BlueZ version (`bluetoothctl -v`) in case of Linux:  No version shown

### Description of problem

Android newbie here.
I have a Simple Windows python app using BLEak framework that works (bluetooth serial data)
I moved to test on android tablet (using pydroid 3) and it shown showed traceback at runtime
```
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 4, in <module>
  File "/storage/emulated/0/0python/BammGUIFS_1_4/comm_BLEak.py", line 14, in <module>
    from bleak import BleakClient
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/bleak/__init__.py", line 41, in <module>
    if not _on_ci and not check_bluez_version(5, 43):
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/bleak/backends/bluezdbus/__init__.py", line 17, in check_bluez_version
    p = subprocess.Popen(["bluetoothctl", "--version"], stdout=subprocess.PIPE)
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/subprocess.py", line 953, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bluetoothctl'
```
Some very sparse info describes flags (READTHEDOCS) set to fix this.  I don't know what to start with.  setting environment variables or somehow installing correct version of bluez.  

https://github.com/hbldh/bleak/discussions/475

I don't understand the resolutions listed here

**Comment by dlech** [comment]
Android support currently only works via python-4-andriod, e.g. with Kivy. See https://github.com/hbldh/bleak/tree/develop/examples/kivy.

If you are using a different Python runtime, then it would need a new backend that calls the Android APIs somehow in that runtime. BlueZ won't work on Android since it already has it's own Bluetooth stack. Unless you are making your own Android builds and can replace the Bluetooth stack.

**Comment by antonelliCP** [comment]
Thanks.  This explains and clarifies the issue.
