### ISSUE TITLE
Android app crash after lunch

### ISSUE THREAD

**Issue by Egidio92** [hbldh/bleak#883]
* bleak version: 0.14.3
* Python version: Python 3.7.13 (Colab)
* Operating System: Samsung SM-G900F Android 6.0.1, API 23

### Description #######################################################

Hello! I am trying to implement an application on an android mobile. This app needs to connect via low-energy bluetooth BLE to a scale (Mi Smart Scale 2) and take the weight. To create the apk of the application I use Colab.
The problem is that when I launch the application it crashes immediately after starting and I cannot read the weight.

### What I Did ########################################################

import asyncio

from kivy.app import App
from kivy.lang.builder import Builder
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.properties import ObjectProperty

from bleak import BleakClient

kv = '''
WindowManager:
    
    MainWindow:
    BluetoothWindow:
    LoginWindow:
    
        
     
    
<LoginWindow>:
    name: "login"

    email: email
    password: password

    FloatLayout:

        Label:
            text:"Email: "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.9}
            size_hint: 0.35, 0.15

        TextInput:
            id: email
            font_size: (root.width**2 + root.height**2) / 13**4
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.9}
            size_hint: 0.4, 0.15

        Label:
            text:"Password: "
            font_size: (root.width**2 + root.height**2) / 13**4
            pos_hint: {"x":0.1, "top":0.7}
            size_hint: 0.35, 0.15

        TextInput:
            id: password
            font_size: (root.width**2 + root.height**2) / 13**4
            multiline: False
            password: True
            pos_hint: {"x": 0.45, "top":0.7}
            size_hint: 0.4, 0.15

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.2
            font_size: (root.width**2 + root.height**2) / 13**4
            text: "Login"
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "left"

        Button:
            pos_hint:{"x":0.2,"y":0.3}
            size_hint: 0.6, 0.1
            font_size: (root.width**2 + root.height**2) / 17**4
            text: "Non hai un account? Creane uno"  
            on_release:
     
                
     
        
     
<MainWindow>:
    name: "main"
    BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
        
    FloatLayout:
        n: n
        email: email
        created:created

        FloatLayout:
            Label:
                id: n
                pos_hint:{"x": 0.1, "top":0.9}
                size_hint:0.8, 0.2
                text: "Nome account: "

            Label:
                id: email
                pos_hint:{"x": 0.1, "top":0.7}
                size_hint:0.8, 0.2
                text: "Email: "

            Label:
                id: created
                pos_hint:{"x": 0.1, "top":0.5}
                size_hint:0.8, 0.2
                text: "Creato il: "

            Button:
                pos_hint:{"x":0.35, "y": 0.2}
                size_hint:0.3,0.1
                text: "Log Out"
                on_release:
                    app.root.current = "login"
                    root.manager.transition.direction = "right"
                

            Button:
                pos_hint:{"x":0.35, "y": 0.1}
                size_hint:0.3,0.1
                text: "Log In"
                on_release:
                    app.root.current = "ble"
                    root.manager.transition.direction = "left"
                
<BluetoothWindow>:
    name: "ble"
    peso: peso

    
    BoxLayout:
		orientation: "vertical"
		size: root.width, root.height

    FloatLayout:
        Label:
            id: peso
            pos_hint:{"x": 0.1, "top":0.7}
            size_hint:0.8, 0.2
            text: "peso: "
        
        Button:
            pos_hint:{"x":0.2, "y": 0.1}
            size_hint:0.6,0.2
            text: "Log Out"
            on_release:
                app.root.current = "main"
                root.manager.transition.direction = "right"
'''

class LoginWindow(Screen):
    pass

class MainWindow(Screen):
    pass

class BluetoothWindow(Screen):
    peso = ObjectProperty(None)
    
    def on_enter(self):

        self.peso.text = "peso: " + str(data2)

class WindowManager(ScreenManager):
    pass

sm = WindowManager()

screens = [MainWindow(name="main"), 
           BluetoothWindow(name="ble"),
           LoginWindow(name="login")]

for screen in screens:
    sm.add_widget(screen)

sm.current = "main"

class AsyncApp(App):

    other_task = None

    def build(self):
        return Builder.load_string(kv)
    
    def build2(self):
        return sm

    def app_func(self):
        '''This will run both methods asynchronously and then block until they
        are finished
        '''
        self.other_task = asyncio.ensure_future(self.get_the_weight_from_the_mi_smart_scale_2())

        async def run_wrapper():
            # we don't actually need to set asyncio as the lib because it is
            # the default, but it doesn't hurt to be explicit
            await self.async_run(async_lib='asyncio')
            print('App done')
            self.other_task.cancel()

        return asyncio.gather(run_wrapper(), self.other_task)
   
    global notification_handler
    def notification_handler(sender, data):
        """Simple notification handler which prints the data received."""
        data1 = list(data)
        global data2
        data2 = ((data1[1]+data1[2]*256)*0.005)
        print("{0}: {1}".format(sender, data2))

    async def get_the_weight_from_the_mi_smart_scale_2(self):
        #da modificare
        '''This method is also run by the asyncio loop and periodically prints
        something.
        '''
        async with BleakClient("70:87:9e:0f:f8:7d") as client:
            print(f"Connected: {client.is_connected}")
            
            await client.start_notify("00002a9d-0000-1000-8000-00805f9b34fb", notification_handler)
            await asyncio.sleep(30.0)
            await client.stop_notify("00002a9d-0000-1000-8000-00805f9b34fb")   
            print(f"Connected: {client.is_connected}")

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(AsyncApp().app_func())
    loop.close()

### What I read on Android Studio's log######################################
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 4
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2477/? W/bt_btif: bta_le_client_conn_param_cback, status : 0
2022-07-13 15:53:26.187 1983-2477/? W/bt_btif: bta_le_client_conn_param_cback, clcb found and client_if : 10
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2204/? D/BtGatt.GattService: onClientConnParamsChanged() - clientIf=10 address=70:87:9E:0F:F8:7D, interval=39status=0
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 3
2022-07-13 15:53:26.187 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 4
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 14122-14134/org.test.tesi4 D/BluetoothGatt: onClientConnParamsChanged() - Device=70:87:9E:0F:F8:7D interval=39 status=0
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 5
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 5
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 5
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 5
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.197 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.207 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 5
2022-07-13 15:53:26.207 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.207 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 5
2022-07-13 15:53:26.207 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.207 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 5
2022-07-13 15:53:26.207 1983-2415/? D/BtGatt.GattService: [gattSrvHandler] msg : 2
2022-07-13 15:53:26.207 14122-14134/org.test.tesi4 D/BluetoothGatt: onSearchComplete() = Device=70:87:9E:0F:F8:7D Status=0
2022-07-13 15:53:26.277 1983-2493/? D/bt_upio: ..proc_btwrite_timeout..
2022-07-13 15:53:26.277 1983-2493/? D/bt_upio: upio_set : pio 0 action 1, polarity 1
2022-07-13 15:53:26.357 14122-14150/org.test.tesi4 I/python: Connected: True
2022-07-13 15:53:26.357 14122-14150/org.test.tesi4 D/BluetoothGatt: cancelOpen() - device: 70:87:9E:0F:F8:7D
2022-07-13 15:53:26.367 1983-2015/? D/BtGatt.GattService: clientDisconnect() - address=70:87:9E:0F:F8:7D, connId=10
2022-07-13 15:53:26.367 1983-2477/? E/bt_btm: btm_ble_get_search_if search_if=4
2022-07-13 15:53:26.367 1983-2417/? D/bt_vendor: op for 7
2022-07-13 15:53:26.367 836-2532/? V/AlarmManager:  remove PendingIntent] PendingIntent{ec8bcc: PendingIntentRecord{83cd4dc com.android.bluetooth broadcastIntent}}
2022-07-13 15:53:26.367 1983-2417/? D/bt_upio: upio_set : pio 0 action 2, polarity 1
2022-07-13 15:53:26.367 1983-2477/? W/bt_btif: bta_gattc_conn_cback() - cif=4 connected=0 conn_id=4 reason=0x0016
2022-07-13 15:53:26.367 1983-2417/? D/bt_upio: upio_start_stop_timer : timer_settime success
2022-07-13 15:53:26.367 1983-2477/? W/bt_btif: bta_gattc_conn_cback() - cif=5 connected=0 conn_id=5 reason=0x0016
2022-07-13 15:53:26.367 1983-2477/? W/bt_btif: bta_gattc_conn_cback() - cif=6 connected=0 conn_id=6 reason=0x0016
2022-07-13 15:53:26.367 1983-2477/? W/bt_btif: bta_gattc_conn_cback() - cif=7 connected=0 conn_id=7 reason=0x0016
2022-07-13 15:53:26.367 1983-2477/? W/bt_btif: bta_gattc_conn_cback() - cif=8 connected=0 conn_id=8 reason=0x0016
2022-07-13 15:53:26.367 1983-2477/? W/bt_btif: bta_gattc_conn_cback() - cif=9 connected=0 conn_id=9 reason=0x0016
2022-07-13 15:53:26.367 1983-2417/? D/bt_upio: upio_set: proc btwrite assertion, buffer: 1, timer_armed 1 1
2022-07-13 15:53:26.367 1983-2477/? W/bt_btif: bta_gattc_conn_cback() - cif=10 connected=0 conn_id=10 reason=0x0016
2022-07-13 15:53:26.367 1983-2477/? E/bt_btif: bta_gattc_mark_bg_conn unable to find the bg connection mask for: 70:87:9e:0f:f8:7d
2022-07-13 15:53:26.367 1983-2204/? D/BtGatt.GattService: onDisconnected() - clientIf=10, connId=10, address=70:87:9E:0F:F8:7D
2022-07-13 15:53:26.367 14122-14157/org.test.tesi4 D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=10 device=70:87:9E:0F:F8:7D
2022-07-13 15:53:26.367 14122-14150/org.test.tesi4 D/BluetoothGatt: close()
2022-07-13 15:53:26.367 14122-14150/org.test.tesi4 D/BluetoothGatt: unregisterApp() - mClientIf=10
2022-07-13 15:53:26.377 1983-2505/? D/BtGatt.GattService: unregisterClient() - clientIf=10
2022-07-13 15:53:26.377 14122-14150/org.test.tesi4 I/python:  Traceback (most recent call last):
2022-07-13 15:53:26.377 14122-14150/org.test.tesi4 I/python:    File "/content/.buildozer/android/app/main.py", line 228, in <module>
2022-07-13 15:53:26.377 836-1510/? V/AlarmManager:  remove PendingIntent] PendingIntent{317de15: PendingIntentRecord{83cd4dc com.android.bluetooth broadcastIntent}}
2022-07-13 15:53:26.377 14122-14150/org.test.tesi4 I/python:    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/asyncio/base_events.py", line 616, in run_until_complete
2022-07-13 15:53:26.377 14122-14150/org.test.tesi4 I/python:    File "/content/.buildozer/android/app/main.py", line 216, in get_the_weight_from_the_mi_smart_scale_2
2022-07-13 15:53:26.377 14122-14150/org.test.tesi4 I/python:    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/tesi4/armeabi-v7a/bleak/backends/p4android/client.py", line 486, in start_notify
2022-07-13 15:53:26.377 14122-14150/org.test.tesi4 I/python:  bleak.exc.BleakError: Characteristic with UUID 00002a9d-0000-1000-8000-00805f9b34fb could not be found!
2022-07-13 15:53:26.377 14122-14150/org.test.tesi4 I/python: Python for android ended.
2022-07-13 15:53:26.387 1983-2477/? I/bt_btm_sec: btm_sec_disconnected clearing pending flag handle:64 reason:22
```

**Comment by Egidio92** [comment]
And this is the buildozer.spec file:

[app]

# (str) Title of your application
title = Demo3

# (str) Package name
package.name = demo3

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin, venv

# (list) List of exclusions using pattern matching
# Do not prefix with './'
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy,pillow,kivymd,asyncio,bleak

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

# change the major version of python used by the app
osx.python_version = 3

# Kivy version to use
osx.kivy_version = 1.9.1

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (for android toolchain)
# Supported formats are: #RRGGBB #AARRGGBB or one of the following names:
# red, blue, green, black, white, gray, cyan, magenta, yellow, lightgray,
# darkgray, grey, lightgrey, darkgrey, aqua, fuchsia, lime, maroon, navy,
# olive, purple, silver, teal.
#android.presplash_color = #FFFFFF

# (string) Presplash animation using Lottie format.
# see https://lottiefiles.com/ for examples and https://airbnb.design/lottie/
# for general documentation.
# Lottie files can be created using various tools, like Adobe After Effect or Synfig.
#android.presplash_lottie = "path/to/lottie/file.json"

# (str) Adaptive icon of the application (used if Android API level is 26+ at runtime)
#icon.adaptive_foreground.filename = %(source.dir)s/data/icon_fg.png
#icon.adaptive_background.filename = %(source.dir)s/data/icon_bg.png

# (list) Permissions
android.permissions = BLUETOOTH,BLUETOOTH_ADMIN,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION,ACCESS_BACKGROUND_LOCATION

# (list) features (adds uses-feature -tags to manifest)
#android.features = android.hardware.usb.host

# (int) Target Android API, should be as high as possible.
#android.api = 27

# (int) Minimum API your APK / AAB will support.
#android.minapi = 21

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 19b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (bool) If True, then automatically accept SDK license
# agreements. This is intended for automation only. If set to False,
# the default, you will be shown the license when first running
# buildozer.
android.accept_sdk_license = True

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.kivy.android.PythonActivity

# (str) Full name including package path of the Java class that implements Android Activity
# use that parameter together with android.entrypoint to set custom Java class instead of PythonActivity
#android.activity_class_name = org.kivy.android.PythonActivity

# (str) Extra xml to write directly inside the <manifest> element of AndroidManifest.xml
# use that parameter to provide a filename from where to load your custom XML code
#android.extra_manifest_xml = ./src/android/extra_manifest.xml

# (str) Extra xml to write directly inside the <manifest><application> tag of AndroidManifest.xml
# use that parameter to provide a filename from where to load your custom XML arguments:
#android.extra_manifest_application_arguments = ./src/android/extra_manifest_application_arguments.xml

# (str) Full name including package path of the Java class that implements Python Service
# use that parameter to set custom Java class instead of PythonService
#android.service_class_name = org.kivy.android.PythonService

# (str) Android app theme, default is ok for Kivy-based app
# android.apptheme = "@android:style/Theme.NoTitleBar"

# (list) Pattern to whitelist for the whole project
#android.whitelist =

# (str) Path to a custom whitelist file
#android.whitelist_src =

# (str) Path to a custom blacklist file
#android.blacklist_src =

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
android.add_src = %(source.dir)s/Java/

# (list) Android AAR archives to add
#android.add_aars =

# (list) Put these files or directories in the apk assets directory.
# Either form may be used, and assets need not be in 'source.include_exts'.
# 1) android.add_assets = source_asset_relative_path
# 2) android.add_assets = source_asset_path:destination_asset_relative_path
#android.add_assets =

# (list) Gradle dependencies to add
#android.gradle_dependencies =

# (bool) Enable AndroidX support. Enable when 'android.gradle_dependencies'
# contains an 'androidx' package, or any package from Kotlin source.
# android.enable_androidx requires android.api >= 28
#android.enable_androidx = False

# (list) add java compile options
# this can for example be necessary when importing certain java libraries using the 'android.gradle_dependencies' option
# see https://developer.android.com/studio/write/java8-support for further information
# android.add_compile_options = "sourceCompatibility = 1.8", "targetCompatibility = 1.8"

# (list) Gradle repositories to add {can be necessary for some android.gradle_dependencies}
# please enclose in double quotes 
# e.g. android.gradle_repositories = "maven { url 'https://kotlin.bintray.com/ktor' }"
#android.add_gradle_repositories =

# (list) packaging options to add 
# see https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
# can be necessary to solve conflicts in gradle_dependencies
# please enclose in double quotes 
# e.g. android.add_packaging_options = "exclude 'META-INF/common.kotlin_module'", "exclude 'META-INF/*.kotlin_module'"
#android.add_packaging_options =

# (list) Java classes to add as activities to the manifest.
#android.add_activities = com.example.ExampleActivity

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (str) launchMode to set for the main activity
#android.manifest.launch_mode = standard

# (list) Android additional libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_arm64_v8a = libs/android-v8/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (list) Android shared libraries which will be added to AndroidManifest.xml using <uses-library> tag
#android.uses_library =

# (str) Android logcat filters to use
android.logcat_filters = *:S python:D

# (bool) Android logcat only display log for activity's pid
#android.logcat_pid_only = False

# (str) Android additional adb arguments
#android.adb_args = -H host.docker.internal

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

# (list) The Android archs to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
# In past, was `android.arch` as we weren't supporting builds for multiple archs at the same time.
android.archs = armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

# (bool) enables Android auto backup feature (Android API >=23)
android.allow_backup = True

# (str) XML file for custom backup rules (see official auto backup documentation)
# android.backup_rules =

# (str) If you need to insert variables into your AndroidManifest.xml file,
# you can do so with the manifestPlaceholders property.
# This property takes a map of key-value pairs. (via a string)
# Usage example : android.manifest_placeholders = [myCustomUrl:\"org.kivy.customurl\"]
# android.manifest_placeholders = [:]

# (bool) disables the compilation of py to pyc/pyo files when packaging
# android.no-compile-pyo = True

# (str) The format used to package the app for release mode (aab or apk).
# android.release_artifact = aab

#
# Python for android (p4a) specific
#

# (str) python-for-android URL to use for checkout
#p4a.url =

# (str) python-for-android fork to use in case if p4a.url is not specified, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master

# (str) python-for-android specific commit to use, defaults to HEAD, must be within p4a.branch
#p4a.commit = HEAD

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#p4a.source_dir =

# (str) The directory in which python-for-android should look for your own build recipes (if any)
#p4a.local_recipes =

# (str) Filename to the hook for p4a
#p4a.hook =

# (str) Bootstrap to use for android builds
# p4a.bootstrap = sdl2

# (int) port number to specify an explicit --port= p4a argument (eg for bootstrap flask)
#p4a.port =

# Control passing the --use-setup-py vs --ignore-setup-py to p4a
# "in the future" --use-setup-py is going to be the default behaviour in p4a, right now it is not
# Setting this to false will pass --ignore-setup-py, true will pass --use-setup-py
# NOTE: this is general setuptools integration, having pyproject.toml is enough, no need to generate
# setup.py if you're using Poetry, but you need to add "toml" to source.include_exts.
#p4a.setup_py = false

# (str) extra command line arguments to pass when invoking pythonforandroid.toolchain
#p4a.extra_args =


#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.10.0

# (bool) Whether or not to sign the code
ios.codesign.allowed = false

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) The development team to use for signing the debug version
#ios.codesign.development_team.debug = <hexstring>

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s

# (str) The development team to use for signing the release version
#ios.codesign.development_team.release = <hexstring>

# (str) URL pointing to .ipa file to be installed
# This option should be defined along with `display_image_url` and `full_size_image_url` options.
#ios.manifest.app_url =

# (str) URL pointing to an icon (57x57px) to be displayed during download
# This option should be defined along with `app_url` and `full_size_image_url` options.
#ios.manifest.display_image_url =

# (str) URL pointing to a large icon (512x512px) to be used by iTunes
# This option should be defined along with `app_url` and `display_image_url` options.
#ios.manifest.full_size_image_url =


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .aab, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

**Comment by dlech** [comment]
> 2022-07-13 15:53:26.377 14122-14150/org.test.tesi4 I/python:  bleak.exc.BleakError: Characteristic with UUID 00002a9d-0000-1000-8000-00805f9b34fb could not be found!

Either there is a bug with characteristic discovery, the android os hides this characteristic or the device does not have this characteristic. If we can rule out the last two, then we can look for a bug in Bleak.

**Comment by Egidio92** [comment]
Thanks for the quick reply. The device has this characteristic (i'm 100% sure) because by launching the same code from Mac it works. What do you advise me to do?

**Comment by Egidio92** [comment]
Of course! I'll answer in about half an hour. I build the apk with Colab. Thank you.

**Comment by dlech** [comment]
> 2022-07-13 18:12:41.390 21906-21935/org.test.tesi6 I/python: {0: <bleak.backends.p4android.characteristic.BleakGATTCharacteristicP4Android object at 0x9a2009e8>}

This shows there is only one characteristic with handle `0` which doesn't seem right. I think we assumed that `getInstanceId()` returned the handle, but I think that it just returns a number that is unique per characteristics with the same UUID. That is, it returns 0 for most characteristics and 1 for the second instance of a characteristic with the same UUID as an already seen characteristic.

So, to fix this, I think we need to create a mapping between a tuple containing the UUID and instance id to a "handle" integer value to be compatible with other Bleak backends.

**Comment by Egidio92** [comment]
Thanks for the replies. However I am trying to solve the problem. 😄

**Comment by Egidio92** [comment]
How can I do to find the one I need? 
That is: "00002a9d-0000-1000-8000-00805f9b34fb" ...Which is the one relating to the weight of the scale passed by BLE

**Comment by Egidio92** [comment]
These days I have done various tests also setting the code differently but I always find only this unique characteristic "00002a00-0000-1000-8000-00805f9b34fb", which should be linked to the name of the device

**Comment by Egidio92** [comment]
Thanks for the reply. I just used the nRF Connect app and my android phone sees that characteristic and the others characteristics too.

**Comment by Egidio92** [comment]
[characteristic.txt](https://github.com/hbldh/bleak/files/9461339/characteristic.txt)
[client.txt](https://github.com/hbldh/bleak/files/9461348/client.txt)
[descriptor.txt](https://github
[service.txt](https://github.com/hbldh/bleak/files/9461355/service.txt)
.com/hbldh/bleak/files/9461354/descriptor.txt)

**Comment by Egidio92** [comment]
[characteristic.txt](https://github.com/hbldh/bleak/files/9461357/characteristic.txt)

[client.txt](https://github.com/hbldh/bleak/files/9461358/client.txt)

[descriptor.txt](https://github.com/hbldh/bleak/files/9461361/descriptor.txt)


[service.txt](https://github.com/hbldh/bleak/files/9461363/service.txt)

**Comment by Egidio92** [comment]
By editing these four files and replacing them in the p4android folder I was able to remap the handles. I don't know if it's a clean result but it worked for me.

**Comment by Egidio92** [comment]
For example, in the characteristic.py file I made sure that an index was added to the value "self.obj.getInstanceId()" for each new service found. Because "self.obj.getInstanceId()" always returns zero for every service, characteristic handle. I don't know if it's correct but it works for me now

**Comment by Egidio92** [comment]
what do you think of my solution?

**Comment by dlech** [comment]
In #888, we discussed relaxing the `int` requirement on the handle property. I think it would be more straight-forward to make the "handle" on Android a tuple of the UUID string and the instance ID.

**Comment by Egidio92** [comment]
Ok perfect I will continue to follow the updates. thank you :)

**Comment by vabt-igd** [comment]
I just now ran into similar issues. 
I have one Ubuntu VM that I have been using for about a year, which is able to build a kivy app for Android that makes heavy usage of bleak. 
Now, to move my dev to a new computer, I created a new Ubuntu VM based on the same version as previous. After compiling the Android app on that VM using the exact same code base as before, the app fails to connect to my BLE devices due to “missing” services and characteristics. Merging @Egidio92 workaround into bleaks current develop branch did help slightly, as to now the app at least is able to find the corresponding services and characteristics, but start_notify does not seem to work. The notify callbacks never get triggered.
I'll try to further investigate the issue...
@dlech regarding #888, is there anything planned regarding the __handle attribute refactoring?

**Comment by dlech** [comment]
No definite plans.
