### ISSUE TITLE
Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist

### ISSUE THREAD

**Issue by ClusterM** [hbldh/bleak#889]
* bleak version:
bleak-0.14.3
* Python version:
Python 3.9.2
* Operating System:
Linux `lovepoint 5.15.48-sunxi64 #22.05.3 SMP Wed Jun 22 07:33:24 UTC 2022 aarch64 GNU/Linux`
* BlueZ version (`bluetoothctl -v`) in case of Linux:
bluetoothctl: 5.55
### Description
Can't execute `bleak/examples/scanner.py`:

```
cluster@lovepoint:~/bleak/examples$ sudo python3 scanner.py
Traceback (most recent call last):
  File "/home/cluster/bleak/examples/scanner.py", line 31, in <module>
    asyncio.run(main(sys.argv[1] if len(sys.argv) == 2 else ADDRESS))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/cluster/bleak/examples/scanner.py", line 26, in main
    device = await BleakScanner.find_device_by_address(address)
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/scanner.py", line 220, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/scanner.py", line 249, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/scanner.py", line 155, in start
    assert_reply(reply)
  File "/usr/local/lib/python3.9/dist-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
```

Same with `bleak/examples/discover.py`:
```
cluster@lovepoint:~/bleak/examples$ python3 discover.py
Traceback (most recent call last):
  File "/home/cluster/bleak/examples/discover.py", line 22, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/cluster/bleak/examples/discover.py", line 16, in main
    devices = await discover()
  File "/home/cluster/.local/lib/python3.9/site-packages/bleak/backends/scanner.py", line 115, in discover
    async with cls(**kwargs) as scanner:
  File "/home/cluster/.local/lib/python3.9/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/home/cluster/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/scanner.py", line 155, in start
    assert_reply(reply)
  File "/home/cluster/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist
```

**Comment by ClusterM** [comment]
I commented out all `assert_reply(reply)` in scanner.py. It doesn't throw exception now but can't find any device.

**Comment by dlech** [comment]
> sudo python3 scanner.py

Sudo is not required and should not be used with Bleak.

> bleak.exc.BleakDBusError: [org.freedesktop.DBus.Error.UnknownObject] Method "SetDiscoveryFilter" with signature "a{sv}" on interface "org.bluez.Adapter1" doesn't exist

It this the same problems as #693?

**Comment by ClusterM** [comment]
> It this the same problems as #693?

Seems like yes.

**Comment by dlech** [comment]
We should probably try to make a better error message for this. Also #524 could help avoid the problem in some cases.
