### ISSUE TITLE
Exception occurred after disconnection triggered from Nordic device

### ISSUE THREAD

**Issue by snowuyl** [hbldh/bleak#936]
* bleak version: 0.15.0a1
* Python version: 3.10.6
* Operating System: Windows 10

### Description
1. bleak connects to Nordic device
2. After bleak connects to Nordic device, trigger disconnecting from Nordic device.
3. Exception occurred

D:\BlePyCmd>python3 main.py
Waiting connecting to ANCS2
E8:20:9F:75:90:08
manual
Q. Quit

Enter an option: Device was disconnected, goodbye.
Exception in thread Thread-1 (_thread_function):
Traceback (most recent call last):
  File "D:\BlePyCmd\main.py", line 97, in _run_uart
    await asyncio.sleep(0.01)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Andy\workspace_Python3_Win10\BlePyCmd\main.py", line 149, in _thread_function
    loop.run_until_complete(_run_uart(bt_mac_address, loop))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError

**Comment by snowuyl** [comment]
[BlePyCmd.zip](https://github.com/hbldh/bleak/files/9313472/BlePyCmd.zip)

**Comment by snowuyl** [comment]
[BlePyCmd.zip](https://github.com/hbldh/bleak/files/9313473/BlePyCmd.zip)
